// HexaCore · Software Supply Chain (SBOM).
// Software bills of materials (CycloneDX / SPDX) are ingested from vendor
// portals and the client's own build pipelines, or generated by binary scans
// of firmware, so "do we use it?" reaches libraries buried inside products.
//
// Library names are fictional open-source-style packages and every
// vulnerability id is a fictional CVE-2026-5xxxx id; products carrying
// vulnerable components come from fictional vendors. Real suppliers from the
// TPRM register only appear as SBOMs requested / missing, or as clean SBOMs.
//
// The headline component of each customer's Critical Vulnerability Response
// advisory is embedded in a handful of vendor products that the asset-level
// match does not see: the "hidden exposure" this module surfaces.
import type { CustomerId, CustomerProfile, Health, Severity } from '../types';
import { rng } from '../../lib/rng';
import { tpSuppliers } from './tprm';
import { vrAdvisory, vrAssets } from './vulnresponse';
import { forCustomer, type CustomerMap } from '../customerMap';

/* =====================================================================
   Types
   ===================================================================== */
export type SbFormat = 'CycloneDX 1.6' | 'CycloneDX 1.5' | 'SPDX 2.3' | 'SPDX 3.0';
export type SbSource = 'Vendor portal' | 'Build pipeline' | 'Generated by scan';
export type SbRequest = 'Not requested' | 'Requested' | 'Promised' | 'Declined';
export type SbVex = 'Affected' | 'Not affected' | 'Under investigation' | 'Fixed';
export type SbLicRisk = 'Permissive' | 'Weak copyleft' | 'Strong copyleft' | 'Unknown';
export type SbOrigin = 'Vendor' | 'In-house';
export type SbTag = 'device' | 'vehicle' | 'ship' | 'app' | 'ot' | 'payments';

export const SB_VEX: SbVex[] = ['Affected', 'Under investigation', 'Not affected', 'Fixed'];
export const SB_VEX_COLOR: Record<SbVex, string> = { Affected: 'var(--sev-critical)', 'Under investigation': 'var(--sev-medium)', 'Not affected': 'var(--good)', Fixed: 'var(--m-matrix)' };
export const SB_VEX_HEX: Record<SbVex, string> = { Affected: '#e0345e', 'Under investigation': '#f0a338', 'Not affected': '#2dd4bf', Fixed: '#a07cfb' };
export const SB_LIC_COLOR: Record<SbLicRisk, string> = { Permissive: 'var(--good)', 'Weak copyleft': 'var(--sev-low)', 'Strong copyleft': 'var(--sev-high)', Unknown: 'var(--sev-medium)' };
export const SB_REQ_COLOR: Record<SbRequest, string> = { 'Not requested': 'var(--text-muted)', Requested: 'var(--sev-medium)', Promised: 'var(--m-matrix)', Declined: 'var(--bad)' };
export const SB_SOURCE_HEX: Record<SbSource | 'Missing', string> = { 'Vendor portal': '#4f8cff', 'Build pipeline': '#2dd4bf', 'Generated by scan': '#a07cfb', Missing: '#e0345e' };
export const SB_STALE_DAYS = 90;

export interface SbVuln { id: string; sev: Severity; cvss: number; title: string; fixedIn: string; advisory?: boolean }
export interface SbComponent {
  id: string;
  name: string;
  ecosystem: string;
  category: string;
  licence: string;
  licRisk: SbLicRisk;
  latest: string;
  maintainer: string;
  desc: string;
  vulns: SbVuln[];
  /** The component behind the customer's headline advisory. */
  advisory?: boolean;
}
export interface SbLib { compId: string; version: string; vex: Record<string, SbVex>; via?: string }
export interface SbModule { name: string; version: string; libs: SbLib[] }
export interface SbSbom { format: SbFormat; source: SbSource; ageDays: number; signed: boolean; tool: string; serial: string }
export interface SbProduct {
  id: string;
  name: string;
  vendor: string;
  origin: SbOrigin;
  category: string;
  tenants: string[];
  tags: SbTag[];
  supplierName?: string;
  supplierId?: string;
  sbom: SbSbom | null;
  request: SbRequest;
  requestDaysAgo: number | null;
  componentCount: number;
  modules: SbModule[];
  instances: number;
  criticality: 1 | 2 | 3 | 4 | 5;
  adv?: 'matched' | 'hidden';
  note?: string;
}
export interface SbUsage { product: SbProduct; module: string; lib: SbLib }
export interface SbCompRow {
  c: SbComponent;
  uses: SbUsage[];
  products: number;
  versions: string[];
  /** Vulnerability instances (vuln × product) by VEX status. */
  vex: Record<SbVex, number>;
  maxSev: Severity | null;
  open: number;
  vulnerable: boolean;
  licFlag: boolean;
}
export interface SbReg { id: string; name: string; short: string; ask: string; scopeLabel: string; test: (p: SbProduct) => boolean }
export interface SbRegRow { reg: SbReg; inScope: SbProduct[]; withSbom: SbProduct[]; pct: number }

/* =====================================================================
   Component catalogue (fictional, open-source-style)
   ===================================================================== */
type CS = Omit<SbComponent, 'id' | 'vulns' | 'maintainer'> & { maintainer?: string; vulns?: SbVuln[] };
const v = (id: string, sev: Severity, cvss: number, title: string, fixedIn: string): SbVuln => ({ id, sev, cvss, title, fixedIn });

const GENERIC: CS[] = [
  { name: 'logweave', ecosystem: 'Maven', category: 'Logging', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '3.4.2', desc: 'Structured logging framework for JVM services', vulns: [v('CVE-2026-51204', 'high', 8.1, 'Message lookup expands attacker-controlled expressions', '3.4.1')] },
  { name: 'tlsforge', ecosystem: 'C / C++', category: 'TLS', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '2.9.4', desc: 'Lightweight TLS 1.2 / 1.3 library for embedded and server builds', vulns: [v('CVE-2026-50877', 'critical', 9.1, 'Heap overflow in certificate-chain parsing', '2.9.3')] },
  { name: 'zstream', ecosystem: 'C / C++', category: 'Compression', licence: 'Zlib', licRisk: 'Permissive', latest: '1.6.1', desc: 'Deflate / inflate stream compression', vulns: [v('CVE-2026-52116', 'medium', 6.5, 'Out-of-bounds read on crafted stream headers', '1.6.0')] },
  { name: 'xmlark', ecosystem: 'C / C++', category: 'XML parsing', licence: 'MIT', licRisk: 'Permissive', latest: '4.2.0', desc: 'Streaming XML parser with schema validation', vulns: [v('CVE-2026-51733', 'high', 8.2, 'External entity expansion reads local files', '4.1.7')] },
  { name: 'jsonette', ecosystem: 'npm', category: 'JSON', licence: 'MIT', licRisk: 'Permissive', latest: '5.1.3', desc: 'Fast JSON parse / serialise for JavaScript' },
  { name: 'httpcore-lite', ecosystem: 'Go', category: 'HTTP client', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '1.12.0', desc: 'Minimal HTTP/1.1 and HTTP/2 client', vulns: [v('CVE-2026-53021', 'medium', 5.9, 'Request smuggling through header folding', '1.11.4')] },
  { name: 'imgdecode', ecosystem: 'C / C++', category: 'Image codec', licence: 'LGPL-2.1', licRisk: 'Weak copyleft', latest: '0.19.2', desc: 'PNG / JPEG / WebP decoding', vulns: [v('CVE-2026-50642', 'high', 7.8, 'Integer overflow in chunk length handling', '0.19.1')] },
  { name: 'sqlbridge', ecosystem: 'Maven', category: 'Database driver', licence: 'GPL-2.0', licRisk: 'Strong copyleft', latest: '8.3.0', desc: 'JDBC driver and connection pool' },
  { name: 'yamlite', ecosystem: 'PyPI', category: 'YAML parsing', licence: 'MIT', licRisk: 'Permissive', latest: '6.0.4', desc: 'YAML loader and dumper', vulns: [v('CVE-2026-52890', 'critical', 9.0, 'Unsafe loader constructs arbitrary objects', '6.0.3')] },
  { name: 'authkit-jwt', ecosystem: 'npm', category: 'Authentication', licence: 'MIT', licRisk: 'Permissive', latest: '9.2.1', desc: 'JSON Web Token sign and verify', vulns: [v('CVE-2026-51467', 'high', 8.6, 'Algorithm confusion allows forged tokens', '9.2.0')] },
  { name: 'cronic', ecosystem: 'PyPI', category: 'Scheduling', licence: 'MIT', licRisk: 'Permissive', latest: '2.3.0', desc: 'Cron-style job scheduler' },
  { name: 'tinyshell', ecosystem: 'Embedded Linux', category: 'System utilities', licence: 'GPL-2.0', licRisk: 'Strong copyleft', latest: '1.38.1', desc: 'Single-binary shell and core utilities for embedded Linux', vulns: [v('CVE-2026-53318', 'medium', 6.7, 'Command injection in the DHCP client hook', '1.38.0')] },
  { name: 'regexa', ecosystem: 'Cargo', category: 'Regex', licence: 'MIT OR Apache-2.0', licRisk: 'Permissive', latest: '1.11.0', desc: 'Regular-expression engine', vulns: [v('CVE-2026-54102', 'low', 3.7, 'Catastrophic backtracking on nested groups', '1.10.6')] },
  { name: 'protolite', ecosystem: 'C / C++', category: 'Serialisation', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '3.27.0', desc: 'Compact binary message serialisation' },
  { name: 'arcunpack', ecosystem: 'Maven', category: 'Archive extraction', licence: 'MIT', licRisk: 'Permissive', latest: '2.4.0', desc: 'ZIP / TAR extraction', vulns: [v('CVE-2026-51988', 'high', 7.5, 'Path traversal writes outside the target folder', '2.3.9')] },
  { name: 'netstack-pico', ecosystem: 'Embedded C', category: 'TCP/IP stack', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '4.6.2', desc: 'Embedded TCP/IP stack for RTOS targets', vulns: [v('CVE-2026-50311', 'high', 8.8, 'Out-of-bounds write in TCP option parsing', '4.6.1')] },
  { name: 'ssh-mini', ecosystem: 'C / C++', category: 'SSH', licence: 'BSD-2-Clause', licRisk: 'Permissive', latest: '0.11.3', desc: 'Embedded SSH server and client', vulns: [v('CVE-2026-52544', 'medium', 5.3, 'Username enumeration through timing', '0.11.2')] },
  { name: 'datefmt', ecosystem: 'npm', category: 'Date & time', licence: 'MIT', licRisk: 'Permissive', latest: '4.0.2', desc: 'Date parsing and formatting' },
  { name: 'pdfgen-core', ecosystem: 'Maven', category: 'Document generation', licence: 'AGPL-3.0', licRisk: 'Strong copyleft', latest: '7.1.4', desc: 'PDF generation and form filling' },
  { name: 'mqtt-pico', ecosystem: 'Embedded C', category: 'Messaging', licence: 'EPL-2.0', licRisk: 'Weak copyleft', latest: '1.5.0', desc: 'MQTT 3.1.1 / 5 client for devices', vulns: [v('CVE-2026-53655', 'medium', 6.5, 'Malformed CONNACK triggers buffer over-read', '1.4.8')] },
  { name: 'uikit-web', ecosystem: 'npm', category: 'UI framework', licence: 'MIT', licRisk: 'Permissive', latest: '18.4.0', desc: 'Component framework for web front ends' },
  { name: 'cryptocore', ecosystem: 'C / C++', category: 'Cryptography', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '3.2.5', desc: 'Symmetric and asymmetric crypto primitives' },
  { name: 'boardfw-sdk', ecosystem: 'Firmware', category: 'Board support', licence: 'Proprietary (unstated)', licRisk: 'Unknown', latest: '2024.2', desc: 'Board support package shipped as a binary blob' },
  { name: 'httpd-embed', ecosystem: 'Embedded C', category: 'Web server', licence: 'MIT', licRisk: 'Permissive', latest: '2.8.1', desc: 'Embedded web server for device management consoles', vulns: [v('CVE-2026-51150', 'high', 8.0, 'Directory traversal in static file handler', '2.8.0')] },
];

const SECTOR_LIBS: CustomerMap<CS[]> = {
  maritime: [
    { name: 'nmea-parse', ecosystem: 'C / C++', category: 'Navigation protocol', licence: 'MIT', licRisk: 'Permissive', latest: '2.2.0', desc: 'NMEA 0183 / 2000 sentence parser', vulns: [v('CVE-2026-52407', 'medium', 6.1, 'Checksum bypass accepts spoofed sentences', '2.1.9')] },
    { name: 'aisdecode', ecosystem: 'PyPI', category: 'Navigation protocol', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '1.4.1', desc: 'AIS message decoder' },
    { name: 'modlink-core', ecosystem: 'Embedded C', category: 'Industrial protocol', licence: 'LGPL-3.0', licRisk: 'Weak copyleft', latest: '3.1.2', desc: 'Modbus TCP / RTU master and slave', vulns: [v('CVE-2026-53880', 'high', 7.5, 'Unbounded register read crashes the slave', '3.1.1')] },
  ],
  finserv: [
    { name: 'iso20022-kit', ecosystem: 'Maven', category: 'Payments messaging', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '5.8.0', desc: 'ISO 20022 message model and validation' },
    { name: 'fixwire', ecosystem: 'C / C++', category: 'Trading protocol', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '2.14.1', desc: 'FIX protocol engine', vulns: [v('CVE-2026-52671', 'high', 7.4, 'Sequence reset handling allows session hijack', '2.14.0')] },
    { name: 'pkcs11-bridge', ecosystem: 'Maven', category: 'HSM integration', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '1.9.3', desc: 'PKCS#11 bridge to hardware security modules' },
  ],
  media: [
    { name: 'ffmux', ecosystem: 'C / C++', category: 'Media container', licence: 'LGPL-2.1', licRisk: 'Weak copyleft', latest: '7.0.2', desc: 'Media container mux / demux', vulns: [v('CVE-2026-51599', 'high', 7.8, 'Heap overflow on crafted MP4 atoms', '7.0.1')] },
    { name: 'subforge', ecosystem: 'Python', category: 'Subtitles', licence: 'GPL-3.0', licRisk: 'Strong copyleft', latest: '3.3.0', desc: 'Subtitle conversion (SRT, TTML, IMSC)' },
    { name: 'hlspack', ecosystem: 'Go', category: 'Streaming packager', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '2.6.0', desc: 'HLS / DASH segmenter and manifest writer', vulns: [v('CVE-2026-53190', 'medium', 5.4, 'Manifest injection through unescaped titles', '2.5.8')] },
  ],
  healthcare: [
    { name: 'hl7tide', ecosystem: 'Maven', category: 'Clinical messaging', licence: 'MPL-2.0', licRisk: 'Weak copyleft', latest: '4.5.1', desc: 'HL7 v2 parser and router', vulns: [v('CVE-2026-52233', 'high', 7.7, 'Segment parsing allows message tampering', '4.5.0')] },
    { name: 'dicomlet', ecosystem: 'C / C++', category: 'Imaging', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '3.7.0', desc: 'DICOM toolkit for imaging viewers and routers', vulns: [v('CVE-2026-51872', 'medium', 6.5, 'Buffer over-read in tag decoding', '3.6.9')] },
    { name: 'fhirlite', ecosystem: 'npm', category: 'Clinical messaging', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '2.9.0', desc: 'FHIR R4 client and resource model' },
  ],
  automotive: [
    { name: 'canframe', ecosystem: 'Embedded C', category: 'Vehicle bus', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '2.0.4', desc: 'CAN / CAN-FD framing and filters', vulns: [v('CVE-2026-53442', 'medium', 6.2, 'Malformed frame length overruns the receive buffer', '2.0.3')] },
    { name: 'someip-lite', ecosystem: 'C / C++', category: 'Vehicle middleware', licence: 'MPL-2.0', licRisk: 'Weak copyleft', latest: '3.4.0', desc: 'SOME/IP service discovery and transport', vulns: [v('CVE-2026-52958', 'high', 8.1, 'Service-discovery spoofing redirects subscriptions', '3.3.9')] },
    { name: 'ota-delta', ecosystem: 'C / C++', category: 'Software update', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '1.8.2', desc: 'Binary delta patching for OTA packages' },
    { name: 'uds-diag', ecosystem: 'Embedded C', category: 'Diagnostics', licence: 'Proprietary (unstated)', licRisk: 'Unknown', latest: '5.2', desc: 'UDS (ISO 14229) diagnostic server' },
  ],
  insurance: [
    { name: 'acord-model', ecosystem: 'Maven', category: 'Insurance messaging', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '2.8.5', desc: 'ACORD XML / JSON message model for policy, billing and claims exchange', vulns: [v('CVE-2026-51355', 'high', 7.5, 'Entity expansion in policy attachments exhausts memory', '2.8.4')] },
    { name: 'ratebook', ecosystem: 'PyPI', category: 'Rating', licence: 'MIT', licRisk: 'Permissive', latest: '3.1.0', desc: 'Rating-table loader and premium calculation helpers' },
    { name: 'tripcapture-sdk', ecosystem: 'Kotlin / Swift', category: 'Telematics', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '3.2.1', desc: 'Phone-sensor trip capture for usage-based insurance', vulns: [v('CVE-2026-52344', 'medium', 6.4, 'Trip data cached unencrypted on the device', '3.2.0')] },
  ],
  defence: [
    { name: 'milbus-frame', ecosystem: 'Embedded C', category: 'Avionics bus', licence: 'MIT', licRisk: 'Permissive', latest: '1.7.4', desc: 'MIL-STD-1553 and ARINC 429 framing helpers', vulns: [v('CVE-2026-53127', 'medium', 6.0, 'Word-count overflow in the 1553 message parser', '1.7.3')] },
    { name: 'mtconnect-lite', ecosystem: 'C / C++', category: 'Machine-tool protocol', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '2.3.2', desc: 'MTConnect agent and adapter for machine-tool data', vulns: [v('CVE-2026-52783', 'high', 7.5, 'Unbounded asset upload exhausts agent memory', '2.3.1')] },
    { name: 'detrtos', ecosystem: 'Embedded C', category: 'Real-time OS', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '4.0.3', desc: 'Deterministic RTOS kernel for flight and test software' },
  ],
  pharma: [
    { name: 'gs1-epcis', ecosystem: 'Maven', category: 'Serialisation', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '4.2.3', desc: 'GS1 DataMatrix and EPCIS event encoding', vulns: [v('CVE-2026-52519', 'medium', 5.9, 'Malformed EPCIS events accepted without validation', '4.2.2')] },
    { name: 'molgraph', ecosystem: 'PyPI', category: 'Cheminformatics', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '2.5.0', desc: 'Molecular graph and descriptor toolkit' },
    { name: 'esign-trail', ecosystem: 'Maven', category: 'Electronic signatures', licence: 'MPL-2.0', licRisk: 'Weak copyleft', latest: '2.0.6', desc: 'Electronic-signature manifestation and audit-trail helpers', vulns: [v('CVE-2026-53366', 'high', 7.1, 'Signature meaning can be changed after signing', '2.0.5')] },
  ],
  sghospital: [
    { name: 'hl7v2-kit', ecosystem: 'Maven', category: 'Clinical messaging', licence: 'MPL-2.0', licRisk: 'Weak copyleft', latest: '3.9.3', desc: 'HL7 v2 parser, validator and router', vulns: [v('CVE-2026-52071', 'high', 7.3, 'Escape-sequence handling lets segments be injected', '3.9.2')] },
    { name: 'dicomweb-js', ecosystem: 'npm', category: 'Imaging', licence: 'MIT', licRisk: 'Permissive', latest: '4.1.0', desc: 'DICOMweb client for browser-based viewers' },
    { name: 'fhir-r4-model', ecosystem: 'NuGet', category: 'Clinical messaging', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '5.1.2', desc: 'FHIR R4 resource model and validator', vulns: [v('CVE-2026-53604', 'medium', 5.3, 'Validator skips profile constraints on contained resources', '5.1.1')] },
  ],
  studio: [
    { name: 'drmwrap', ecosystem: 'C / C++', category: 'Content protection', licence: 'Proprietary (unstated)', licRisk: 'Unknown', latest: '6.2', desc: 'Multi-DRM licence request wrapper for streaming players' },
    { name: 'abr-player', ecosystem: 'npm', category: 'Streaming player', licence: 'Apache-2.0', licRisk: 'Permissive', latest: '4.7.3', desc: 'Adaptive-bitrate HLS / DASH player core', vulns: [v('CVE-2026-51932', 'medium', 6.1, 'Manifest URL handling allows script injection in the web player', '4.7.2')] },
    { name: 'artnet-io', ecosystem: 'Embedded C', category: 'Show-control protocol', licence: 'LGPL-2.1', licRisk: 'Weak copyleft', latest: '1.9.2', desc: 'Art-Net / sACN lighting and show-control I/O', vulns: [v('CVE-2026-53059', 'high', 7.4, 'Unauthenticated packets change universe patching', '1.9.1')] },
    { name: 'ble-bond', ecosystem: 'Embedded C', category: 'Bluetooth LE', licence: 'BSD-3-Clause', licRisk: 'Permissive', latest: '2.4.1', desc: 'BLE pairing and bonding for wearables', vulns: [v('CVE-2026-52266', 'medium', 6.3, 'Legacy pairing fallback weakens link keys', '2.4.0')] },
  ],
};

/** The component behind each customer's headline advisory (see vulnresponse HEADLINE). */
const ADV_COMP: CustomerMap<CS & { module: string; vulnTitle: string }> = {
  maritime: { name: 'rlink-agent', ecosystem: 'Embedded C', category: 'Remote access', licence: 'Proprietary (Tessaro OEM licence)', licRisk: 'Unknown', latest: '5.4.3', maintainer: 'Tessaro Industrial', desc: 'Tessaro RemoteLink agent library, licensed to OEMs who build remote diagnostics into their own equipment', module: 'Remote service agent', vulnTitle: 'Authentication bypass in the embedded management service' },
  finserv: { name: 'edgegate-portal-core', ecosystem: 'C / C++', category: 'Remote access', licence: 'Proprietary (Corvane OEM licence)', licRisk: 'Unknown', latest: '9.6.5', maintainer: 'Corvane Networks', desc: 'Corvane EdgeGate portal and tunnel core, licensed to OEMs for built-in remote-access modules', module: 'Remote access module', vulnTitle: 'Pre-authentication memory corruption in the portal service' },
  media: { name: 'filestream-engine', ecosystem: 'Maven', category: 'File transfer', licence: 'Proprietary (Larkspur SDK licence)', licRisk: 'Unknown', latest: '2026.2.4', maintainer: 'Larkspur Software', desc: 'Larkspur FileStream transfer engine SDK, embedded by tools that move media files', module: 'Transfer engine', vulnTitle: 'Unauthenticated injection in the embedded web transfer interface' },
  healthcare: { name: 'interlink-core', ecosystem: 'Maven', category: 'Clinical integration', licence: 'Proprietary (Halden OEM licence)', licRisk: 'Unknown', latest: '7.8.2', maintainer: 'Halden Health Systems', desc: 'Halden InterLink engine core, embedded by device and lab vendors to speak HL7 / FHIR', module: 'Interface engine', vulnTitle: 'Authentication bypass in the embedded administration API' },
  automotive: { name: 'novalink-rs', ecosystem: 'Firmware', category: 'Remote service', licence: 'Proprietary (Strelitz OEM licence)', licRisk: 'Unknown', latest: 'V3.4.2', maintainer: 'Strelitz Automation', desc: 'Strelitz NovaLink remote-service module, embedded in machine builders’ controllers', module: 'Remote-service module', vulnTitle: 'Missing authentication on the remote-service channel' },
  insurance: { name: 'securexchange-core', ecosystem: 'NuGet', category: 'File transfer', licence: 'Proprietary (Bramwell SDK licence)', licRisk: 'Unknown', latest: '2026.1.5', maintainer: 'Bramwell Software', desc: 'Bramwell SecureXchange transfer core, embedded by claims, recovery and payment platforms that exchange files with partners', module: 'File exchange engine', vulnTitle: 'Unauthenticated injection in the embedded transfer web service' },
  defence: { name: 'perimeterone-tunnel', ecosystem: 'C / C++', category: 'Remote access', licence: 'Proprietary (Talgarth OEM licence)', licRisk: 'Unknown', latest: '7.5.4', maintainer: 'Talgarth Networks', desc: 'Talgarth PerimeterOne portal and tunnel core, licensed to equipment makers for built-in remote-support access', module: 'Remote support module', vulnTitle: 'Pre-authentication code execution in the embedded portal service' },
  pharma: { name: 'processbridge-ua', ecosystem: 'C / C++', category: 'Industrial protocol (OPC UA)', licence: 'Proprietary (Velden OEM licence)', licRisk: 'Unknown', latest: '4.6.3', maintainer: 'Velden Systems', desc: 'Velden ProcessBridge OPC UA server stack, embedded by bioreactor, lyophiliser and skid makers to publish process data', module: 'OPC UA server', vulnTitle: 'Authentication bypass in the embedded configuration service' },
  sghospital: { name: 'routemaster-dicom', ecosystem: 'C / C++', category: 'Imaging (DICOM)', licence: 'Proprietary (Sorrell OEM licence)', licRisk: 'Unknown', latest: '6.3.5', maintainer: 'Sorrell Imaging', desc: 'Sorrell RouteMaster DICOM routing core, embedded by dose-monitoring, imaging-AI and workstation vendors', module: 'DICOM router', vulnTitle: 'Authentication bypass in the embedded web administration service' },
  studio: { name: 'streamport-sdk', ecosystem: 'C / C++', category: 'File transfer', licence: 'Proprietary (Quillon SDK licence)', licRisk: 'Unknown', latest: '5.8.2', maintainer: 'Quillon Media', desc: 'Quillon StreamPort accelerated-transfer SDK, embedded by dailies, review and show-media tools to move large files', module: 'Accelerated transfer', vulnTitle: 'Unauthenticated path traversal in the embedded transfer web service' },
};

/* =====================================================================
   Product seeds per sector
   ===================================================================== */
type Code = 'c6' | 'c5' | 's2' | 's3' | 'scan' | null;
interface PSeed {
  n: string; vendor: string; cat: string; o: 'V' | 'I' | 'S'; t: string[]; s: Code;
  tags?: SbTag[]; adv?: 'matched' | 'hidden'; sup?: string; req?: SbRequest; reqDays?: number; mods?: string[]; inst?: number; crit?: 1 | 2 | 3 | 4 | 5; note?: string; advVer?: string; advVex?: SbVex;
}

const PRODUCTS: CustomerMap<PSeed[]> = {
  maritime: [
    { n: 'Tessaro RemoteLink OT Gateway', vendor: 'Tessaro Industrial', cat: 'OT remote-access gateway', o: 'V', t: ['rtm', 'ant', 'pkl', 'sts', 'fleet'], s: 'c5', tags: ['ot', 'ship'], adv: 'matched', inst: 18, crit: 5, mods: ['Web management service', 'Cloud relay', 'Firmware base'], advVer: '5.4.2' },
    { n: 'Halvard CraneSight Remote Diagnostics', vendor: 'Halvard Lifting Systems', cat: 'Crane condition monitoring', o: 'V', t: ['rtm', 'ant', 'pkl'], s: 'c6', tags: ['ot'], adv: 'hidden', inst: 46, crit: 5, mods: ['Drive telemetry collector', 'Operator HMI', 'Firmware base'], advVer: '5.3.1', note: 'Installed on every STS crane; vendor diagnostics dial home through the embedded RemoteLink agent.' },
    { n: 'Morrow ReeferWatch Telemetry Hub', vendor: 'Morrow Cold Chain', cat: 'Reefer stack monitoring', o: 'V', t: ['rtm', 'ant', 'sts'], s: 's2', tags: ['ot'], adv: 'hidden', inst: 12, crit: 4, mods: ['Reefer poller', 'Alarm gateway', 'Firmware base'], advVer: '5.2.0', advVex: 'Under investigation' },
    { n: 'Brightwater FleetLink Bridge Console', vendor: 'Brightwater Marine Electronics', cat: 'Vessel IT/OT gateway', o: 'V', t: ['fleet'], s: 'scan', tags: ['ship', 'ot'], adv: 'hidden', inst: 22, crit: 5, mods: ['Bridge data concentrator', 'Shore sync', 'Firmware base'], advVer: '5.1.4', note: 'SBOM generated by binary analysis of the firmware image; the vendor has not published one.' },
    { n: 'Halcyon Berth Planner', vendor: 'Halcyon Group Digital', cat: 'In-house planning app', o: 'I', t: ['hq', 'rtm', 'ant'], s: 'c6', inst: 3, crit: 4, mods: ['Planner API', 'Web front end', 'Optimiser jobs'] },
    { n: 'Halcyon Crew Portal', vendor: 'Halcyon Group Digital', cat: 'In-house crew web app', o: 'I', t: ['hq', 'fleet'], s: 'c6', tags: ['app'], inst: 2, crit: 3, mods: ['Portal API', 'Web front end', 'Document service'] },
    { n: 'Keelson ECDIS Chart Server', vendor: 'Keelson Nautical', cat: 'Bridge navigation software', o: 'V', t: ['fleet'], s: 's2', tags: ['ship'], inst: 22, crit: 5, mods: ['Chart engine', 'Sensor ingest', 'Update client'] },
    { n: 'Quayline Gate OCR Server', vendor: 'Quayline Systems', cat: 'Gate automation', o: 'V', t: ['rtm', 'ant', 'pkl', 'sts'], s: 'c5', tags: ['ot'], inst: 9, crit: 3, mods: ['OCR engine', 'Lane controller', 'Web console'] },
    { n: 'Norvik Historian', vendor: 'Norvik Data', cat: 'OT data historian', o: 'V', t: ['rtm', 'ant', 'pkl'], s: 'scan', tags: ['ot'], inst: 3, crit: 4, mods: ['Collector service', 'Archive engine', 'Web console'] },
    { n: 'Brightfield VSAT Terminal Manager', vendor: 'Brightfield Marine', cat: 'Satellite terminal management', o: 'V', t: ['fleet'], s: 'c5', tags: ['ship'], inst: 22, crit: 4, mods: ['Terminal agent', 'Web console', 'Firmware base'] },
    { n: 'Tidal PortSense Mooring Monitor', vendor: 'Tidal Instruments', cat: 'Mooring load sensors', o: 'V', t: ['rtm', 'pkl'], s: 'c6', tags: ['ot'], inst: 6, crit: 3, mods: ['Sensor gateway', 'Firmware base'] },
    { n: 'STS crane remote-service gateway', vendor: 'Konecranes Remote Services', cat: 'OT vendor remote access', o: 'S', t: ['rtm', 'ant', 'pkl', 'sts'], s: null, sup: 'Konecranes Remote Services', req: 'Requested', reqDays: 12, tags: ['ot'], inst: 31, crit: 5 },
    { n: 'Terminal operating system', vendor: 'Navis (Kaleris)', cat: 'Terminal operating system', o: 'S', t: ['rtm', 'ant', 'pkl', 'sts'], s: null, sup: 'Navis (Kaleris)', req: 'Promised', reqDays: 26, inst: 4, crit: 5 },
    { n: 'Engine & cargo control software', vendor: 'Kongsberg Maritime', cat: 'Vessel automation', o: 'S', t: ['fleet'], s: null, sup: 'Kongsberg Maritime', req: 'Not requested', tags: ['ship', 'ot'], inst: 22, crit: 5 },
    { n: 'AGV fleet controller software', vendor: 'Vanderlande Automation', cat: 'AGV & yard automation', o: 'S', t: ['rtm'], s: null, sup: 'Vanderlande Automation', req: 'Requested', reqDays: 5, tags: ['ot'], inst: 1, crit: 4 },
    { n: 'Fleet ERP & crew system', vendor: 'Wallem Ship Management', cat: 'Technical ship management', o: 'S', t: ['fleet', 'hq'], s: null, sup: 'Wallem Ship Management', req: 'Declined', reqDays: 40, inst: 1, crit: 3 },
    { n: 'Gate OCR camera firmware', vendor: 'Cargotec Gate OCR', cat: 'Gate automation', o: 'S', t: ['rtm', 'ant', 'pkl', 'sts'], s: 'c5', sup: 'Cargotec Gate OCR', tags: ['ot'], inst: 64, crit: 2, mods: ['Camera firmware', 'Lane I/O'] },
  ],
  finserv: [
    { n: 'Corvane EdgeGate SSL VPN', vendor: 'Corvane Networks', cat: 'VPN / remote-access gateway', o: 'V', t: ['ukbank', 'eu', 'markets', 'pay'], s: 'c5', adv: 'matched', inst: 10, crit: 5, mods: ['Portal service', 'Tunnel daemon', 'Admin console'], advVer: '9.6.4' },
    { n: 'Pellam BranchEdge SD-WAN Router', vendor: 'Pellam Networks', cat: 'Branch router', o: 'V', t: ['ukbank', 'eu'], s: 'c6', adv: 'hidden', inst: 214, crit: 4, mods: ['Routing plane', 'Management UI', 'Firmware base'], advVer: '9.5.1', note: 'Branch routers in 214 branches ship an EdgeGate-based remote access module for engineer support.' },
    { n: 'Ostra ATM Fleet Manager', vendor: 'Ostra Self-Service', cat: 'ATM estate management', o: 'V', t: ['ukbank'], s: 's2', tags: ['payments'], adv: 'hidden', inst: 2, crit: 5, mods: ['Fleet console', 'Terminal agent', 'Reporting'], advVer: '9.4.2', note: 'Remote terminal support for 1,860 ATMs runs over an embedded EdgeGate tunnel.' },
    { n: 'Varden Secure Remote Support Appliance', vendor: 'Varden Software', cat: 'Remote support appliance', o: 'V', t: ['markets', 'wealth'], s: 'scan', adv: 'hidden', inst: 3, crit: 4, mods: ['Session broker', 'Web console', 'Firmware base'], advVer: '9.6.2', advVex: 'Under investigation' },
    { n: 'Aldersgate Mobile Banking', vendor: 'Aldersgate Digital', cat: 'In-house mobile app (iOS / Android)', o: 'I', t: ['ukbank', 'eu'], s: 'c6', tags: ['app', 'payments'], inst: 2, crit: 5, mods: ['App shell', 'Payments SDK', 'Auth module'] },
    { n: 'Open Banking API platform', vendor: 'Aldersgate Digital', cat: 'In-house API platform', o: 'I', t: ['ukbank', 'pay'], s: 'c6', tags: ['payments'], inst: 6, crit: 5, mods: ['API gateway', 'Consent service', 'Token service'] },
    { n: 'Ledgerline Payment Hub', vendor: 'Ledgerline', cat: 'Payment message gateway', o: 'V', t: ['pay', 'ukbank'], s: 'c5', tags: ['payments'], inst: 3, crit: 5, mods: ['Message router', 'REST API', 'Admin console'] },
    { n: 'Card authorisation switch', vendor: 'Aldersgate Payments Engineering', cat: 'In-house card switch', o: 'I', t: ['pay'], s: 's2', tags: ['payments'], inst: 4, crit: 5, mods: ['Auth engine', 'HSM adapter', 'Scheme connectors'] },
    { n: 'Tallis AppStream Gateway', vendor: 'Tallis Software', cat: 'Application delivery gateway', o: 'V', t: ['wealth'], s: 'scan', inst: 2, crit: 3, mods: ['Session proxy', 'Web console'] },
    { n: 'Private Wealth client portal', vendor: 'Aldersgate Digital', cat: 'In-house web portal', o: 'I', t: ['wealth'], s: 'c6', tags: ['app'], inst: 2, crit: 4, mods: ['Portal API', 'Web front end', 'Statement service'] },
    { n: 'Corbel OMS', vendor: 'Corbel Trading Systems', cat: 'Order management', o: 'V', t: ['markets'], s: 's2', inst: 4, crit: 5, mods: ['Order engine', 'FIX gateway', 'Blotter UI'] },
    { n: 'Core banking platform (T24)', vendor: 'Temenos', cat: 'Core banking', o: 'S', t: ['ukbank', 'eu'], s: null, sup: 'Temenos', req: 'Promised', reqDays: 21, inst: 2, crit: 5 },
    { n: 'Card issuing & processing platform', vendor: 'FIS', cat: 'Card processing', o: 'S', t: ['pay'], s: null, sup: 'FIS', req: 'Requested', reqDays: 9, tags: ['payments'], inst: 1, crit: 5 },
    { n: 'Treasury management (SaaS)', vendor: 'Kyriba', cat: 'Treasury SaaS', o: 'S', t: ['ukbank', 'eu'], s: null, sup: 'Kyriba', req: 'Requested', reqDays: 17, inst: 1, crit: 3 },
    { n: 'Lending platform (maintained)', vendor: 'Sopra Steria', cat: 'Application maintenance', o: 'S', t: ['ukbank'], s: 'c5', sup: 'Sopra Steria', inst: 3, crit: 4, mods: ['Origination service', 'Decision engine'] },
    { n: 'Back-office workflow suite', vendor: 'Infosys BPM', cat: 'Outsourced operations', o: 'S', t: ['ukbank', 'eu', 'wealth'], s: null, sup: 'Infosys BPM', req: 'Not requested', inst: 1, crit: 3 },
  ],
  media: [
    { n: 'Larkspur FileStream MFT', vendor: 'Larkspur Software', cat: 'Managed file transfer', o: 'V', t: ['post', 'studios', 'live'], s: 'c5', adv: 'matched', inst: 9, crit: 5, mods: ['Web transfer interface', 'Transfer service', 'Admin console'], advVer: '2026.2.3' },
    { n: 'Vellum Dailies Uploader', vendor: 'Vellum Media Tools', cat: 'On-set dailies upload', o: 'V', t: ['studios', 'post'], s: 'c6', adv: 'hidden', inst: 38, crit: 5, mods: ['Upload client', 'Checksum service', 'Desktop UI'], advVer: '2026.1.0', note: 'On-set DIT carts push camera originals through an embedded FileStream engine.' },
    { n: 'Cadence Subtitle Workstation', vendor: 'Cadence Lingua Software', cat: 'Subtitle & localisation', o: 'V', t: ['post'], s: 's2', adv: 'hidden', inst: 24, crit: 4, mods: ['Timeline editor', 'Vendor exchange', 'Render queue'], advVer: '2025.4.1', advVex: 'Under investigation' },
    { n: 'Halyard Playout Ingest Gateway', vendor: 'Halyard Broadcast', cat: 'Playout ingest', o: 'V', t: ['live'], s: 'scan', tags: ['ot'], adv: 'hidden', inst: 4, crit: 5, mods: ['Ingest watcher', 'Transcode bridge', 'Firmware base'], advVer: '2025.4.1' },
    { n: 'KestrelPlay TV app', vendor: 'KestrelPlay Engineering', cat: 'In-house TV app (Android TV, tvOS, web)', o: 'I', t: ['play'], s: 'c6', tags: ['app'], inst: 3, crit: 5, mods: ['Player', 'Catalogue UI', 'DRM client'] },
    { n: 'KestrelPlay mobile app', vendor: 'KestrelPlay Engineering', cat: 'In-house mobile app', o: 'I', t: ['play'], s: 'c6', tags: ['app'], inst: 2, crit: 5, mods: ['Player', 'Downloads', 'Account module'] },
    { n: 'KestrelPlay packaging & DRM backend', vendor: 'KestrelPlay Engineering', cat: 'In-house streaming backend', o: 'I', t: ['play'], s: 'c6', inst: 14, crit: 5, mods: ['Packager', 'Licence service', 'Manifest API'] },
    { n: 'Corvid Render Queue Manager', vendor: 'Corvid Systems', cat: 'Render farm scheduler', o: 'V', t: ['post'], s: 'c5', inst: 4, crit: 4, mods: ['Scheduler', 'Worker agent', 'Web console'] },
    { n: 'Kestrel Screener Portal', vendor: 'Kestrel Studios Technology', cat: 'In-house screener platform', o: 'I', t: ['studios'], s: 'c6', tags: ['app'], inst: 2, crit: 5, mods: ['Portal API', 'Watermark service', 'Web front end'] },
    { n: 'Ostrander Playout Controller', vendor: 'Ostrander Broadcast', cat: 'Broadcast playout automation', o: 'V', t: ['live'], s: 'scan', tags: ['ot'], inst: 2, crit: 5, mods: ['Control API', 'Schedule engine'] },
    { n: 'Beacon Metrics Player SDK', vendor: 'Beacon Metrics', cat: 'Player analytics SDK', o: 'V', t: ['play'], s: 'c6', inst: 3, crit: 3, mods: ['Telemetry SDK'] },
    { n: 'Playout automation suite', vendor: 'Grass Valley', cat: 'Broadcast systems', o: 'S', t: ['live'], s: null, sup: 'Grass Valley', req: 'Requested', reqDays: 8, tags: ['ot'], inst: 2, crit: 5 },
    { n: 'Dailies review platform (SaaS)', vendor: 'Cinesite Review Cloud', cat: 'Dailies & review', o: 'S', t: ['studios', 'post'], s: null, sup: 'Cinesite Review Cloud', req: 'Promised', reqDays: 19, inst: 1, crit: 4 },
    { n: 'VFX pipeline toolkit', vendor: 'Lumière VFX (Montréal)', cat: 'VFX vendor tooling', o: 'S', t: ['post'], s: null, sup: 'Lumière VFX (Montréal)', req: 'Not requested', inst: 1, crit: 4 },
    { n: 'IMF mastering & delivery', vendor: 'Deluxe Distribution', cat: 'Mastering & delivery', o: 'S', t: ['studios'], s: 's2', sup: 'Deluxe Distribution', inst: 1, crit: 4, mods: ['Mastering service', 'Delivery client'] },
  ],
  healthcare: [
    { n: 'Halden InterLink integration engine', vendor: 'Halden Health Systems', cat: 'Clinical integration engine', o: 'V', t: ['mrmc', 'kids', 'community', 'research'], s: 'c5', adv: 'matched', inst: 15, crit: 5, mods: ['Administration API', 'Channel runtime', 'Message store'], advVer: '7.8.1' },
    { n: 'Corrin LabBridge Middleware', vendor: 'Corrin Diagnostics', cat: 'Lab analyser middleware', o: 'V', t: ['mrmc', 'community'], s: 's2', adv: 'hidden', inst: 5, crit: 5, mods: ['Analyser drivers', 'Results router', 'QC module'], advVer: '7.6.0', note: 'Routes analyser results to Epic Beaker through an embedded InterLink engine.' },
    { n: 'Aldis PharmaFlow Dispensing Server', vendor: 'Aldis Medical', cat: 'Pharmacy automation', o: 'V', t: ['mrmc', 'kids'], s: 'c6', tags: ['device'], adv: 'hidden', inst: 3, crit: 5, mods: ['Dispense queue', 'Order interface', 'Cabinet sync'], advVer: '7.7.2' },
    { n: 'Trellis Bedside Device Hub', vendor: 'Trellis Medical', cat: 'Bedside device integration', o: 'V', t: ['mrmc', 'kids', 'community'], s: 'scan', tags: ['device'], adv: 'hidden', inst: 140, crit: 5, mods: ['Device drivers', 'Flowsheet bridge', 'Firmware base'], advVer: '7.4.3', advVex: 'Under investigation', note: 'FDA-cleared configuration: changes need the manufacturer’s validated build.' },
    { n: 'Calder PACS Web Viewer', vendor: 'Calder Imaging', cat: 'Imaging viewer (PACS)', o: 'V', t: ['mrmc', 'research'], s: 'c5', inst: 3, crit: 4, mods: ['Viewer front end', 'Study router', 'Link service'] },
    { n: 'Wexley Pump Library Server', vendor: 'Wexley Medical', cat: 'Infusion drug library', o: 'V', t: ['community'], s: 'c6', tags: ['device'], inst: 3, crit: 5, mods: ['Library service', 'Pump sync', 'Web console'] },
    { n: 'Ardent Nurse-Call Server', vendor: 'Ardent Clinical', cat: 'Nurse-call platform', o: 'V', t: ['mrmc', 'kids', 'community'], s: 's2', tags: ['device'], inst: 7, crit: 4, mods: ['Call engine', 'Badge gateway'] },
    { n: 'MyMercy patient app', vendor: 'Mercy Ridge Digital Health', cat: 'In-house patient app', o: 'I', t: ['clinics', 'mrmc'], s: 'c6', tags: ['app'], inst: 2, crit: 4, mods: ['App shell', 'Scheduling module', 'Messaging module'] },
    { n: 'Genomics analysis pipeline', vendor: 'Mercy Ridge Research IT', cat: 'In-house research pipeline', o: 'I', t: ['research'], s: 'c6', inst: 1, crit: 3, mods: ['Workflow runner', 'Variant caller wrapper', 'Results API'] },
    { n: 'EHR platform (hosted)', vendor: 'Epic Systems', cat: 'Electronic health record', o: 'S', t: ['mrmc', 'kids', 'community', 'clinics'], s: null, sup: 'Epic Systems', req: 'Promised', reqDays: 30, inst: 1, crit: 5 },
    { n: 'Patient monitoring gateway', vendor: 'Philips Healthcare', cat: 'Patient monitoring', o: 'S', t: ['mrmc', 'kids'], s: null, sup: 'Philips Healthcare', req: 'Requested', reqDays: 11, tags: ['device'], inst: 6, crit: 5 },
    { n: 'Infusion pump server & drug library', vendor: 'BD (Becton Dickinson)', cat: 'Infusion pumps', o: 'S', t: ['mrmc', 'kids', 'community'], s: 'c5', sup: 'BD (Becton Dickinson)', tags: ['device'], inst: 4, crit: 5, mods: ['Pump server', 'Library editor'] },
    { n: 'CT & MRI modality software', vendor: 'GE HealthCare', cat: 'Imaging OEM', o: 'S', t: ['mrmc', 'kids'], s: 's2', sup: 'GE HealthCare', tags: ['device'], inst: 11, crit: 5, mods: ['Acquisition software', 'Remote service agent'] },
    { n: 'Reference lab results interface', vendor: 'Synapse Pathology Labs', cat: 'Reference laboratory', o: 'S', t: ['mrmc', 'community'], s: null, sup: 'Synapse Pathology Labs', req: 'Not requested', inst: 1, crit: 3 },
    { n: 'Dispensing cabinet software', vendor: 'Omnicell', cat: 'Pharmacy automation', o: 'S', t: ['mrmc', 'kids', 'community'], s: null, sup: 'Omnicell', req: 'Requested', reqDays: 6, tags: ['device'], inst: 210, crit: 4 },
  ],
  automotive: [
    { n: 'Strelitz NovaLink PLC runtime', vendor: 'Strelitz Automation', cat: 'PLC firmware', o: 'V', t: ['ingolstadt', 'gyor', 'battery', 'puebla'], s: 'c5', tags: ['ot'], adv: 'matched', inst: 21, crit: 5, mods: ['Controller runtime', 'Remote-service channel', 'Firmware base'], advVer: 'V3.4.1' },
    { n: 'Raskin RoboCell Controller', vendor: 'Raskin Robotics', cat: 'Robot cell controller', o: 'V', t: ['ingolstadt', 'puebla'], s: 'c6', tags: ['ot'], adv: 'hidden', inst: 64, crit: 5, mods: ['Motion runtime', 'Safety PLC bridge', 'Firmware base'], advVer: 'V3.3.0', note: 'Body-shop robot cells embed the NovaLink remote-service module for the machine builder’s support line.' },
    { n: 'Ferrand Paint Cell Supervisor', vendor: 'Ferrand Finishing Systems', cat: 'Paint shop supervisory control', o: 'V', t: ['ingolstadt'], s: 's2', tags: ['ot'], adv: 'hidden', inst: 8, crit: 4, mods: ['Recipe manager', 'Cell HMI', 'Firmware base'], advVer: 'V3.1.2' },
    { n: 'Oberon Formation Rack Controller', vendor: 'Oberon Battery Equipment', cat: 'Cell formation & ageing', o: 'V', t: ['battery'], s: 'scan', tags: ['ot'], adv: 'hidden', inst: 36, crit: 5, mods: ['Charge profiles', 'Rack I/O', 'Firmware base'], advVer: 'V3.2.0', advVex: 'Under investigation', note: 'Air-gapped plant: the SBOM was generated offline and brought in with the last HexaOT bundle.' },
    { n: 'Vireo TCU firmware', vendor: 'Vireo Vehicle Software', cat: 'In-house telematics firmware', o: 'I', t: ['connected'], s: 'c6', tags: ['vehicle'], inst: 2100000, crit: 5, mods: ['Modem manager', 'OTA client', 'Vehicle bus gateway'] },
    { n: 'VIOS 4 infotainment', vendor: 'Vireo Vehicle Software', cat: 'In-house head-unit software', o: 'I', t: ['connected'], s: 's3', tags: ['vehicle'], inst: 1450000, crit: 5, mods: ['Media stack', 'App runtime', 'Connectivity'] },
    { n: 'Vireo Connect app', vendor: 'Vireo Digital', cat: 'In-house mobile app', o: 'I', t: ['connected'], s: 'c6', tags: ['app'], inst: 2, crit: 4, mods: ['App shell', 'Remote commands', 'Account module'] },
    { n: 'OTA campaign backend', vendor: 'Vireo Vehicle Software', cat: 'In-house update service (SUMS)', o: 'I', t: ['connected'], s: 'c6', tags: ['vehicle'], inst: 18, crit: 5, mods: ['Campaign service', 'Package signer', 'Delta builder'] },
    { n: 'Vireo Home Charger firmware', vendor: 'Vireo Energy', cat: 'In-house charger firmware', o: 'I', t: ['connected'], s: 'c6', tags: ['app'], inst: 182000, crit: 3, mods: ['Charge controller', 'Wi-Fi provisioning', 'Firmware base'] },
    { n: 'Torvald MES Connector', vendor: 'Torvald Software', cat: 'MES integration middleware', o: 'V', t: ['ingolstadt', 'gyor', 'puebla'], s: 'c5', tags: ['ot'], inst: 6, crit: 4, mods: ['Message bus adapter', 'Order sync'] },
    { n: 'Kessler Robot Remote Service', vendor: 'Kessler Robotics', cat: 'Robot remote-service module', o: 'V', t: ['puebla'], s: 'scan', tags: ['ot'], inst: 4, crit: 4, mods: ['Service agent', 'Firmware base'] },
    { n: 'ADAS domain controller software', vendor: 'Bosch Mobility', cat: 'Tier 1 ECU software', o: 'S', t: ['connected'], s: 'c6', sup: 'Bosch Mobility', tags: ['vehicle'], inst: 980000, crit: 5, mods: ['Perception stack', 'Diagnostics'] },
    { n: 'TCU modem & connectivity stack', vendor: 'Continental Automotive', cat: 'Tier 1 telematics', o: 'S', t: ['connected'], s: null, sup: 'Continental Automotive', req: 'Promised', reqDays: 14, tags: ['vehicle'], inst: 2100000, crit: 5 },
    { n: 'Robot controller remote service', vendor: 'KUKA Robotics', cat: 'Robot OEM', o: 'S', t: ['ingolstadt', 'gyor'], s: null, sup: 'KUKA Robotics', req: 'Requested', reqDays: 7, tags: ['ot'], inst: 410, crit: 5 },
    { n: 'MES & engineering tool projects', vendor: 'Siemens Digital Industries', cat: 'PLC, MES & engineering tools', o: 'S', t: ['ingolstadt', 'gyor', 'battery', 'puebla'], s: null, sup: 'Siemens Digital Industries', req: 'Promised', reqDays: 22, tags: ['ot'], inst: 12, crit: 5 },
    { n: 'Dealer management SaaS', vendor: 'DealerCore DMS', cat: 'Dealer management', o: 'S', t: ['retail'], s: null, sup: 'DealerCore DMS', req: 'Declined', reqDays: 33, inst: 1, crit: 3 },
  ],
  insurance: [
    { n: 'Bramwell SecureXchange MFT', vendor: 'Bramwell Software', cat: 'Managed file transfer', o: 'V', t: ['group', 'claims', 'personal', 'life', 'commercial'], s: 'c5', adv: 'matched', inst: 7, crit: 5, mods: ['Transfer web service', 'Transfer engine', 'Admin console'], advVer: '2026.1.4' },
    { n: 'Clarion ClaimsBridge TPA Exchange', vendor: 'Clarion Claims Software', cat: 'TPA & adjuster file exchange', o: 'V', t: ['claims'], s: 'c6', adv: 'hidden', inst: 4, crit: 5, mods: ['Assignment feed', 'Document sync', 'Adjuster portal'], advVer: '2025.4.0', note: 'Sends claim files to independent adjusters and TPAs through an embedded SecureXchange engine.' },
    { n: 'Sexton Recovery Hub', vendor: 'Sexton Subrogation Systems', cat: 'Subrogation & recovery exchange', o: 'V', t: ['claims', 'commercial'], s: 's2', adv: 'hidden', inst: 2, crit: 4, mods: ['Demand packages', 'Carrier exchange', 'Recovery ledger'], advVer: '2025.2.1', advVex: 'Under investigation', note: 'Inter-carrier demand packages travel through the embedded transfer engine; the vendor has been asked for a VEX statement.' },
    { n: 'Ledgerfield Premium Lockbox Connector', vendor: 'Ledgerfield Payments', cat: 'Premium payment file exchange', o: 'V', t: ['personal', 'life'], s: 'scan', tags: ['payments'], adv: 'hidden', inst: 2, crit: 5, mods: ['Bank file poller', 'Reconciliation', 'Appliance base'], advVer: '2025.4.0', note: 'SBOM generated by binary analysis of the appliance image; the vendor has not published one.' },
    { n: 'Kingsbridge Mobile', vendor: 'Kingsbridge Digital', cat: 'In-house policyholder app (iOS / Android)', o: 'I', t: ['personal', 'life'], s: 'c6', tags: ['app', 'payments'], inst: 2, crit: 5, mods: ['App shell', 'Claims FNOL module', 'Payments module'] },
    { n: 'Kingsbridge AgentHub portal', vendor: 'Kingsbridge Digital', cat: 'In-house agent & broker portal', o: 'I', t: ['personal', 'commercial', 'specialty'], s: 'c6', tags: ['app'], inst: 4, crit: 5, mods: ['Quote & bind API', 'Web front end', 'Commission statements'] },
    { n: 'DriveWise telematics SDK', vendor: 'Kingsbridge Telematics Engineering', cat: 'In-house telematics SDK (UBI)', o: 'I', t: ['personal'], s: 'c6', tags: ['app'], inst: 2, crit: 4, mods: ['Trip capture', 'Scoring client', 'Upload service'] },
    { n: 'Claims photo-estimating integration', vendor: 'Kingsbridge Claims Engineering', cat: 'In-house integration (ClaimCenter to CCC)', o: 'I', t: ['claims'], s: 'c6', inst: 3, crit: 4, mods: ['Assignment service', 'Photo upload relay', 'Estimate import'] },
    { n: 'Premium payment gateway', vendor: 'Kingsbridge Payments Engineering', cat: 'In-house payment service (CDE)', o: 'I', t: ['personal', 'commercial'], s: 's2', tags: ['payments'], inst: 4, crit: 5, mods: ['Tokenisation client', 'Payment API', 'Settlement jobs'] },
    { n: 'Pennant AgentGate Portal Server', vendor: 'Pennant Labs', cat: 'Agent & broker portal gateway', o: 'V', t: ['personal', 'commercial', 'specialty'], s: 'c5', inst: 3, crit: 4, mods: ['Quote API', 'Session service'] },
    { n: 'Larch Telematics Ingest Broker', vendor: 'Larch Analytics', cat: 'Telematics data ingestion', o: 'V', t: ['personal'], s: 'scan', inst: 2, crit: 4, mods: ['Ingest API', 'Trip normaliser'] },
    { n: 'Holbrook PrintStream Composer', vendor: 'Holbrook Systems', cat: 'Document composition (policy print)', o: 'V', t: ['group'], s: 'c5', inst: 2, crit: 3, mods: ['Template engine', 'Spool manager'] },
    { n: 'Ardley PowerNet UPS card', vendor: 'Ardley Power', cat: 'UPS network management card (data centre)', o: 'V', t: ['group'], s: 'c6', tags: ['ot'], inst: 6, crit: 3, mods: ['Web server', 'SNMP agent', 'Firmware base'] },
    { n: 'PolicyCenter, ClaimCenter & BillingCenter', vendor: 'Guidewire', cat: 'Core insurance platform (SaaS)', o: 'S', t: ['personal', 'commercial', 'claims'], s: null, sup: 'Guidewire', req: 'Promised', reqDays: 24, inst: 1, crit: 5 },
    { n: 'Specialty policy admin (OnDemand)', vendor: 'Duck Creek Technologies', cat: 'Policy admin (Specialty E&S)', o: 'S', t: ['specialty'], s: null, sup: 'Duck Creek Technologies', req: 'Requested', reqDays: 9, inst: 1, crit: 4 },
    { n: 'Life & annuity policy admin', vendor: 'Majesco', cat: 'Life & annuity policy admin', o: 'S', t: ['life'], s: null, sup: 'Majesco', req: 'Not requested', inst: 1, crit: 4 },
    { n: 'Telematics platform & sensor SDK', vendor: 'Cambridge Mobile Telematics', cat: 'Usage-based insurance telematics', o: 'S', t: ['personal'], s: 'c5', sup: 'Cambridge Mobile Telematics', inst: 1, crit: 4, mods: ['Sensor SDK', 'Trip API'] },
    { n: 'Premium payments & disbursements', vendor: 'One Inc', cat: 'Premium payments & claims disbursements', o: 'S', t: ['personal', 'commercial', 'claims'], s: null, sup: 'One Inc', req: 'Declined', reqDays: 38, tags: ['payments'], inst: 1, crit: 5 },
  ],
  defence: [
    { n: 'Talgarth PerimeterOne VPN', vendor: 'Talgarth Networks', cat: 'VPN / remote-access gateway', o: 'V', t: ['programs', 'engineering', 'corporate', 'tucson'], s: 'c5', adv: 'matched', inst: 5, crit: 5, mods: ['Portal service', 'Tunnel daemon', 'Admin console'], advVer: '7.5.3' },
    { n: 'Gresham Spindle Monitor Edge', vendor: 'Gresham Machine Analytics', cat: 'Spindle condition monitoring', o: 'V', t: ['manufacturing'], s: 'c6', tags: ['ot'], adv: 'hidden', inst: 9, crit: 4, mods: ['Vibration collector', 'Edge analytics', 'Firmware base'], advVer: '7.4.1', note: 'Edge units on each machining centre give the maker remote support through an embedded PerimeterOne module.' },
    { n: 'Albright Environmental Chamber Controller', vendor: 'Albright Test Equipment', cat: 'Environmental test chamber control', o: 'V', t: ['tucson'], s: 's2', tags: ['ot'], adv: 'hidden', inst: 4, crit: 4, mods: ['Profile runner', 'Chamber HMI', 'Firmware base'], advVer: '7.3.0', advVex: 'Under investigation', note: 'Chamber remote diagnostics run over an embedded PerimeterOne tunnel; the maker has been asked for a VEX statement.' },
    { n: 'Moraine CMM Controller', vendor: 'Moraine Metrology', cat: 'CMM controller', o: 'V', t: ['manufacturing'], s: 'scan', tags: ['ot'], adv: 'hidden', inst: 2, crit: 4, mods: ['Measurement runtime', 'Programme import', 'Firmware base'], advVer: '7.4.1', note: 'SBOM generated by binary analysis of the controller image; the remote-support module was found inside.' },
    { n: 'Guidance subsystem flight software', vendor: 'Sentry Peak Avionics Engineering', cat: 'In-house flight software (DO-178C)', o: 'I', t: ['engineering', 'programs'], s: 'c6', inst: 3, crit: 5, mods: ['Navigation filter', 'Actuator control', 'Built-in test'] },
    { n: 'ATE test executive & sequences', vendor: 'Sentry Peak Test Engineering', cat: 'In-house automated test software', o: 'I', t: ['tucson', 'engineering'], s: 'c6', tags: ['ot'], inst: 14, crit: 5, mods: ['Sequence engine', 'Instrument drivers', 'Results logger'] },
    { n: 'DNC gateway (Teamcenter to shop floor)', vendor: 'Sentry Peak Manufacturing Systems', cat: 'In-house release integration', o: 'I', t: ['manufacturing', 'engineering'], s: 'c6', tags: ['ot'], inst: 2, crit: 5, mods: ['Release listener', 'Checksum service', 'DNC push client'] },
    { n: 'Range telemetry decoder', vendor: 'Sentry Peak Test Engineering', cat: 'In-house telemetry processing', o: 'I', t: ['tucson'], s: 's2', inst: 2, crit: 4, mods: ['Frame sync', 'Decommutation', 'Display export'] },
    { n: 'Corlis DNC Programme Server', vendor: 'Corlis Machine Data', cat: 'DNC programme distribution', o: 'V', t: ['manufacturing'], s: 'c5', tags: ['ot'], inst: 4, crit: 5, mods: ['Programme upload service', 'Cell controller agent'] },
    { n: 'Ravelin Telemetry Ground Station', vendor: 'Ravelin Data', cat: 'Range telemetry processing', o: 'V', t: ['tucson'], s: 'scan', tags: ['ot'], inst: 2, crit: 4, mods: ['Web console', 'Stream processor'] },
    { n: 'Teamcenter PLM & NX CAM', vendor: 'Siemens Digital Industries Software', cat: 'PLM & CAD tooling', o: 'S', t: ['engineering', 'programs'], s: 'c5', sup: 'Siemens Digital Industries Software', inst: 2, crit: 5, mods: ['PLM server', 'CAM post-processors'] },
    { n: 'CNC control software', vendor: 'Haas Automation', cat: 'CNC machine OEM', o: 'S', t: ['manufacturing'], s: null, sup: 'Haas Automation', req: 'Requested', reqDays: 10, tags: ['ot'], inst: 14, crit: 5 },
    { n: 'Costpoint GovCloud', vendor: 'Deltek', cat: 'ERP SaaS (Costpoint GovCloud)', o: 'S', t: ['corporate', 'programs'], s: null, sup: 'Deltek', req: 'Promised', reqDays: 19, inst: 1, crit: 4 },
    { n: 'Managed Access Gateway', vendor: 'Exostar', cat: 'Supplier identity & collaboration portal', o: 'S', t: ['programs', 'corporate'], s: null, sup: 'Exostar', req: 'Not requested', inst: 1, crit: 3 },
    { n: 'Range telemetry receivers', vendor: 'Desert Sky Telemetry', cat: 'Range telemetry services', o: 'S', t: ['tucson'], s: null, sup: 'Desert Sky Telemetry', req: 'Declined', reqDays: 41, tags: ['ot'], inst: 3, crit: 4 },
    { n: 'Simulation suite (on-prem licence)', vendor: 'Ansys', cat: 'Simulation software', o: 'S', t: ['engineering'], s: 's2', sup: 'Ansys', inst: 1, crit: 3, mods: ['Solver', 'Licence client'] },
  ],
  pharma: [
    { n: 'Velden ProcessBridge OPC UA Gateway', vendor: 'Velden Systems', cat: 'OT data gateway (OPC UA)', o: 'V', t: ['valais', 'cork'], s: 'c5', tags: ['ot'], adv: 'matched', inst: 15, crit: 5, mods: ['Configuration service', 'UA server', 'Historian bridge'], advVer: '4.6.2' },
    { n: 'Lindqvist BioCtrl Bioreactor Controller', vendor: 'Lindqvist Bioprocess', cat: 'Single-use bioreactor controller', o: 'V', t: ['valais'], s: 'c6', tags: ['ot'], adv: 'hidden', inst: 8, crit: 5, mods: ['Control runtime', 'Batch interface', 'Firmware base'], advVer: '4.5.1', note: 'Publishes batch data to PAS-X and PI through an embedded ProcessBridge UA server.' },
    { n: 'Ostmark Lyophiliser HMI', vendor: 'Ostmark Pharmatech', cat: 'Lyophiliser control HMI', o: 'V', t: ['cork'], s: 's2', tags: ['ot'], adv: 'hidden', inst: 4, crit: 5, mods: ['HMI runtime', 'Recipe manager', 'OS image'], advVer: '4.2.0', advVex: 'Under investigation', note: 'Lyophiliser data reaches the Cork historian through the HMI’s embedded UA server; the OEM is confirming whether the configuration service is enabled.' },
    { n: 'Arneson CIP/SIP Skid Controller', vendor: 'Arneson Process Systems', cat: 'Clean-in-place skid control', o: 'V', t: ['valais', 'cork'], s: 'scan', tags: ['ot'], adv: 'hidden', inst: 6, crit: 4, mods: ['Sequence runtime', 'Skid HMI', 'Gateway image'], advVer: '4.5.1', note: 'SBOM generated by binary analysis of the skid gateway image; the vendor has not published one.' },
    { n: 'PAS-X MES integrations', vendor: 'Rhenara Manufacturing IT', cat: 'In-house MES interfaces (PAS-X to SAP & DCS)', o: 'I', t: ['valais', 'cork'], s: 'c6', tags: ['ot'], inst: 6, crit: 5, mods: ['SAP order bridge', 'DCS recipe bridge', 'Batch record export'] },
    { n: 'Rhenara Connect patient-support app', vendor: 'Rhenara Digital', cat: 'In-house patient-support app (iOS / Android)', o: 'I', t: ['commercial'], s: 'c6', tags: ['app'], inst: 2, crit: 4, mods: ['App shell', 'Dose reminders', 'Nurse appointment booking'] },
    { n: 'RhenaPen connected autoinjector', vendor: 'Rhenara Device Engineering', cat: 'In-house combination-product firmware', o: 'I', t: ['commercial', 'rnd'], s: 'c6', tags: ['device', 'app'], inst: 46000, crit: 5, mods: ['Dose sensor', 'BLE link', 'Bootloader'] },
    { n: 'MolGen platform', vendor: 'Rhenara Computational Chemistry', cat: 'In-house generative chemistry platform', o: 'I', t: ['rnd'], s: 'c6', inst: 3, crit: 5, mods: ['Model service', 'Compound registry sync', 'Notebook front end'] },
    { n: 'Serialisation master-data service', vendor: 'Rhenara Supply Chain IT', cat: 'In-house serialisation software (EU FMD / DSCSA)', o: 'I', t: ['cork', 'commercial'], s: 's2', inst: 2, crit: 5, mods: ['Serial number allocator', 'EMVS / DSCSA reporter', 'GS1 encoder'] },
    { n: 'Aldwych LabView Reporting Client', vendor: 'Aldwych Informatics', cat: 'LIMS web reporting client', o: 'V', t: ['corporate', 'cork', 'valais'], s: 'c5', inst: 3, crit: 4, mods: ['Report server', 'Bulk-edit API'] },
    { n: 'Brisco SerialLink Line Controller', vendor: 'Brisco Serialisation', cat: 'Serialisation & aggregation (Level 3)', o: 'V', t: ['cork'], s: 'scan', tags: ['ot'], inst: 3, crit: 5, mods: ['Line-master API', 'Aggregation engine'] },
    { n: 'DeltaV DCS', vendor: 'Emerson', cat: 'DCS OEM (DeltaV)', o: 'S', t: ['valais'], s: 'c5', sup: 'Emerson', tags: ['ot'], inst: 2, crit: 5, mods: ['Controller firmware', 'ProPlus workstation'] },
    { n: 'PAS-X MES (vendor core)', vendor: 'Körber Pharma', cat: 'MES vendor (Werum PAS-X)', o: 'S', t: ['valais', 'cork'], s: null, sup: 'Körber Pharma', req: 'Promised', reqDays: 18, tags: ['ot'], inst: 2, crit: 5 },
    { n: 'SIMATIC PCS 7 & PLC firmware', vendor: 'Siemens', cat: 'Automation OEM (PCS 7, PLCs)', o: 'S', t: ['valais'], s: null, sup: 'Siemens', req: 'Requested', reqDays: 7, tags: ['ot'], inst: 1, crit: 5 },
    { n: 'Rave EDC & RTSM', vendor: 'Medidata (Dassault Systèmes)', cat: 'EDC & randomisation (RTSM)', o: 'S', t: ['clinops'], s: null, sup: 'Medidata (Dassault Systèmes)', req: 'Requested', reqDays: 12, inst: 1, crit: 5 },
    { n: 'Vault QMS, eTMF & CRM', vendor: 'Veeva Systems', cat: 'Quality, clinical & CRM SaaS', o: 'S', t: ['corporate', 'clinops', 'commercial'], s: null, sup: 'Veeva Systems', req: 'Not requested', inst: 1, crit: 4 },
    { n: 'Contract fill-finish line software', vendor: 'Catalent', cat: 'Fill-finish & packaging CMO', o: 'S', t: ['cork'], s: null, sup: 'Catalent', req: 'Declined', reqDays: 35, tags: ['ot'], inst: 1, crit: 3 },
  ],
  sghospital: [
    { n: 'Sorrell RouteMaster DICOM Gateway', vendor: 'Sorrell Imaging', cat: 'Imaging gateway (DICOM / PACS)', o: 'V', t: ['obh', 'labimg', 'specialist', 'daysurg'], s: 'c5', tags: ['device'], adv: 'matched', inst: 11, crit: 5, mods: ['Web administration service', 'Routing engine', 'Study cache'], advVer: '6.3.4' },
    { n: 'Kallis DoseTrack Monitor', vendor: 'Kallis Radiology Software', cat: 'Radiation dose monitoring', o: 'V', t: ['obh', 'labimg'], s: 'c6', tags: ['device'], adv: 'hidden', inst: 2, crit: 4, mods: ['Dose collector', 'Reporting', 'Listener service'], advVer: '6.3.1', note: 'Collects dose reports from every CT through an embedded RouteMaster router.' },
    { n: 'Sorvine Chest X-ray Triage Appliance', vendor: 'Sorvine AI', cat: 'Imaging AI appliance', o: 'V', t: ['obh', 'labimg'], s: 's2', tags: ['device'], adv: 'hidden', inst: 2, crit: 4, mods: ['Inference engine', 'Worklist bridge', 'Appliance base'], advVer: '6.2.0', advVex: 'Under investigation', note: 'HSA-registered AI software; the vendor has been asked for a VEX statement under the GL-04 procurement terms.' },
    { n: 'Halvorsen Ultrasound Workstation', vendor: 'Halvorsen Medical', cat: 'Ultrasound review workstation', o: 'V', t: ['specialist', 'obh'], s: 'scan', tags: ['device'], adv: 'hidden', inst: 9, crit: 3, mods: ['Review software', 'Export service', 'OS image'], advVer: '6.0.2', note: 'SBOM generated by binary analysis of the workstation image; the OEM supplies none for this model, which also runs an unsupported Windows build.' },
    { n: 'Orchid Bay patient app', vendor: 'Orchid Bay Digital', cat: 'In-house patient app (iOS / Android)', o: 'I', t: ['corp', 'obh'], s: 'c6', tags: ['app'], inst: 2, crit: 4, mods: ['App shell', 'Appointments', 'Bill payment'] },
    { n: 'TrakCare integrations (HealthShare interfaces)', vendor: 'Orchid Bay Clinical Applications', cat: 'In-house interface code (TrakCare, LIS, PACS)', o: 'I', t: ['obh', 'specialist', 'daysurg', 'labimg'], s: 'c6', inst: 6, crit: 5, mods: ['ADT feeds', 'Results routing', 'Orders interface'] },
    { n: 'NEHR contribution adapter', vendor: 'Orchid Bay Clinical Applications', cat: 'In-house NEHR submission service', o: 'I', t: ['obh', 'specialist', 'daysurg', 'labimg'], s: 's2', inst: 2, crit: 5, mods: ['Record mapper', 'HealthConnect client', 'Reconciliation'] },
    { n: 'Ashcombe ClinView Portal', vendor: 'Ashcombe Health', cat: 'Clinician web portal', o: 'V', t: ['obh', 'specialist'], s: 'c5', inst: 3, crit: 3, mods: ['Portal API', 'SSO bridge'] },
    { n: 'Wynford DoseLib Sync', vendor: 'Wynford Medical', cat: 'Infusion drug-library distribution', o: 'V', t: ['obh'], s: 'scan', tags: ['device'], inst: 2, crit: 5, mods: ['Library service', 'Pump sync'] },
    { n: 'TrakCare EHR (IRIS platform)', vendor: 'InterSystems', cat: 'Electronic health record (TrakCare)', o: 'S', t: ['obh', 'specialist', 'daysurg', 'labimg'], s: null, sup: 'InterSystems', req: 'Promised', reqDays: 27, inst: 1, crit: 5 },
    { n: 'Alaris infusion system & pump server', vendor: 'BD (Becton Dickinson)', cat: 'Infusion pumps', o: 'S', t: ['obh', 'specialist', 'daysurg'], s: 'c5', sup: 'BD (Becton Dickinson)', tags: ['device'], inst: 3, crit: 5, mods: ['Pump server', 'Drug library editor'] },
    { n: 'Agilia pumps & Vigilant software', vendor: 'Fresenius Kabi', cat: 'Infusion pumps (Agilia)', o: 'S', t: ['obh', 'daysurg'], s: null, sup: 'Fresenius Kabi', req: 'Requested', reqDays: 8, tags: ['device'], inst: 2, crit: 5 },
    { n: 'IntelliVue monitoring & PACS', vendor: 'Philips', cat: 'Patient monitoring & PACS', o: 'S', t: ['obh', 'specialist'], s: null, sup: 'Philips', req: 'Requested', reqDays: 14, tags: ['device'], inst: 4, crit: 5 },
    { n: 'CT modality software', vendor: 'GE HealthCare', cat: 'Imaging OEM (CT, MRI)', o: 'S', t: ['obh', 'labimg'], s: 's2', sup: 'GE HealthCare', tags: ['device'], inst: 4, crit: 5, mods: ['Acquisition software', 'Remote service agent'] },
    { n: 'MRI & lab automation software', vendor: 'Siemens Healthineers', cat: 'Imaging & lab automation', o: 'S', t: ['labimg', 'obh'], s: null, sup: 'Siemens Healthineers', req: 'Not requested', tags: ['device'], inst: 3, crit: 4 },
    { n: 'Telehealth & chatbot platform', vendor: 'CareLink Telehealth', cat: 'Telehealth & patient chatbot platform', o: 'S', t: ['corp', 'daysurg'], s: null, sup: 'CareLink Telehealth', req: 'Declined', reqDays: 33, tags: ['app'], inst: 1, crit: 3 },
  ],
  studio: [
    { n: 'Quillon StreamPort Transfer Server', vendor: 'Quillon Media', cat: 'Accelerated file transfer', o: 'V', t: ['studios', 'post', 'play', 'corp'], s: 'c5', adv: 'matched', inst: 9, crit: 5, mods: ['Transfer web service', 'Transfer engine', 'Admin console'], advVer: '5.8.1' },
    { n: 'Delmar DIT Offload Station', vendor: 'Delmar Camera Systems', cat: 'On-set offload & dailies upload', o: 'V', t: ['studios'], s: 'c6', adv: 'hidden', inst: 26, crit: 5, mods: ['Offload engine', 'Checksum verifier', 'Upload client'], advVer: '5.7.2', note: 'Every DIT cart pushes camera originals to the pre-release vault through an embedded StreamPort SDK.' },
    { n: 'Vantaggio Conform & Review Server', vendor: 'Vantaggio Post Systems', cat: 'Conform & remote review', o: 'V', t: ['post'], s: 's2', adv: 'hidden', inst: 6, crit: 4, mods: ['Review session server', 'Conform engine', 'Vendor sync'], advVer: '5.6.0', advVex: 'Under investigation' },
    { n: 'Lumenline Show Media Server', vendor: 'Lumenline Show Systems', cat: 'Projection & LED media server', o: 'V', t: ['parks', 'parksasia'], s: 'scan', tags: ['ot'], adv: 'hidden', inst: 18, crit: 5, mods: ['Playback engine', 'Content ingest', 'Firmware base'], advVer: '5.6.0', note: 'SBOM generated by binary analysis; nightly show-content updates arrive through the embedded StreamPort SDK.' },
    { n: 'Starfall+ iOS app', vendor: 'Starfall+ Engineering', cat: 'In-house streaming app (iOS / iPadOS)', o: 'I', t: ['play'], s: 'c6', tags: ['app', 'payments'], inst: 2, crit: 5, mods: ['Player', 'Downloads', 'Account & billing'] },
    { n: 'Starfall+ Android & TV apps', vendor: 'Starfall+ Engineering', cat: 'In-house streaming apps (Android, TV platforms)', o: 'I', t: ['play'], s: 'c6', tags: ['app'], inst: 5, crit: 5, mods: ['Player', 'Catalogue UI', 'DRM client'] },
    { n: 'Starfall+ DRM licence service', vendor: 'Starfall+ Engineering', cat: 'In-house DRM licence service', o: 'I', t: ['play'], s: 'c6', inst: 12, crit: 5, mods: ['Licence API', 'Key service', 'Entitlement check'] },
    { n: 'StarPass wearable firmware', vendor: 'Starfall Parks Technology', cat: 'In-house wearable band firmware', o: 'I', t: ['parks', 'parksasia'], s: 'c6', tags: ['app', 'payments'], inst: 410000, crit: 4, mods: ['BLE stack', 'NFC payment applet', 'Bootloader'] },
    { n: 'StarPass app', vendor: 'Starfall Parks Technology', cat: 'In-house resort app (iOS / Android)', o: 'I', t: ['parks', 'parksasia'], s: 'c6', tags: ['app', 'payments'], inst: 2, crit: 4, mods: ['Tickets & virtual queue', 'Wearable pairing', 'Checkout'] },
    { n: 'Thornbury FlexKey Licence Server', vendor: 'Thornbury Licensing', cat: 'Floating licence server (VFX tools)', o: 'V', t: ['post', 'studios'], s: 'c5', inst: 3, crit: 4, mods: ['Vendor daemon', 'Licence manager'] },
    { n: 'Corbin CueMaster Show Controller', vendor: 'Corbin Show Systems', cat: 'Show control system', o: 'V', t: ['parksasia'], s: 'scan', tags: ['ot'], inst: 3, crit: 5, mods: ['Cue API', 'Timeline engine'] },
    { n: 'Ride control firmware (safety PLC)', vendor: 'Intamin', cat: 'Ride manufacturer (OEM)', o: 'S', t: ['parks', 'parksasia'], s: null, sup: 'Intamin', req: 'Requested', reqDays: 11, tags: ['ot'], inst: 46, crit: 5 },
    { n: 'Projection systems firmware', vendor: 'Christie Digital', cat: 'Projection systems OEM', o: 'S', t: ['parks', 'parksasia'], s: 's2', sup: 'Christie Digital', tags: ['ot'], inst: 120, crit: 4, mods: ['Projector firmware', 'Network control'] },
    { n: 'Ticketing & virtual queue platform', vendor: 'accesso', cat: 'Ticketing & queueing', o: 'S', t: ['parks', 'parksasia'], s: null, sup: 'accesso', req: 'Promised', reqDays: 16, tags: ['payments'], inst: 1, crit: 5 },
    { n: 'Screener platform (SaaS)', vendor: 'Indee', cat: 'Screener platform', o: 'S', t: ['studios'], s: null, sup: 'Indee', req: 'Not requested', inst: 1, crit: 4 },
    { n: 'VFX pipeline toolkit', vendor: 'Northlight Pixel (Vancouver)', cat: 'VFX vendor', o: 'S', t: ['post'], s: null, sup: 'Northlight Pixel (Vancouver)', req: 'Declined', reqDays: 29, inst: 1, crit: 4 },
  ],
};

/* =====================================================================
   Regulations per sector
   ===================================================================== */
const has = (p: SbProduct, ...t: SbTag[]) => t.some((x) => p.tags.includes(x));
const inT = (p: SbProduct, ...ids: string[]) => p.tenants.some((x) => ids.includes(x));

const REGS: CustomerMap<SbReg[]> = {
  maritime: [
    { id: 'e27', name: 'IACS UR E27 rev.1', short: 'IACS E27', ask: 'System suppliers deliver a software inventory and a security update plan for every computer-based system on ships contracted from July 2024.', scopeLabel: 'Ship systems', test: (p) => has(p, 'ship') },
    { id: 'e26', name: 'IACS UR E26 rev.1', short: 'IACS E26', ask: 'Owners keep a vessel asset inventory down to the software and firmware versions of each CBS.', scopeLabel: 'Fleet software', test: (p) => inT(p, 'fleet') },
    { id: 'nis2', name: 'NIS2 (port operator, Art. 21)', short: 'NIS2', ask: 'Supply-chain security and vulnerability handling, including the security of the software each supplier provides.', scopeLabel: 'Terminal OT & IT', test: (p) => inT(p, 'rtm', 'ant', 'hq') },
    { id: 'iec62443', name: 'IEC 62443-2-4 / 4-1', short: 'IEC 62443', ask: 'Service providers and product suppliers disclose components and patch status of automation products.', scopeLabel: 'OT products', test: (p) => has(p, 'ot') },
  ],
  finserv: [
    { id: 'dora', name: 'DORA (EU 2022/2554) Art. 8 & 28', short: 'DORA', ask: 'Identify every ICT asset and dependency, and register ICT third-party services with the software they provide.', scopeLabel: 'All ICT products', test: () => true },
    { id: 'pci', name: 'PCI DSS v4.0.1 req. 6.3.2', short: 'PCI DSS', ask: 'Keep an inventory of bespoke and custom software and the third-party components in it, to manage vulnerabilities.', scopeLabel: 'Card data environment', test: (p) => has(p, 'payments') || inT(p, 'pay') },
    { id: 'cra', name: 'EU Cyber Resilience Act', short: 'CRA', ask: 'Manufacturers of products with digital elements sold in the EU draw up an SBOM and handle vulnerabilities for the support period.', scopeLabel: 'In-house apps in the EU', test: (p) => p.origin === 'In-house' && has(p, 'app') },
    { id: 'nydfs', name: 'NYDFS 23 NYCRR 500.13', short: 'NYDFS', ask: 'Asset inventory covering software, its owner and its supported status.', scopeLabel: 'US entities', test: (p) => inT(p, 'markets') },
  ],
  media: [
    { id: 'cra', name: 'EU Cyber Resilience Act', short: 'CRA', ask: 'Streaming apps sold or offered in the EU need an SBOM and a vulnerability-handling process for their support period.', scopeLabel: 'KestrelPlay apps', test: (p) => p.origin === 'In-house' && has(p, 'app') },
    { id: 'tpn', name: 'TPN Gold Shield (MPA CSBP)', short: 'TPN', ask: 'Software that touches pre-release content is inventoried, supported and patched; vendor tools are reviewed.', scopeLabel: 'Content-handling tools', test: (p) => inT(p, 'studios', 'post') },
    { id: 'soc2', name: 'SOC 2 CC7.1 / CC8.1', short: 'SOC 2', ask: 'Detect vulnerabilities in system components and manage change to them (KestrelPlay attestation).', scopeLabel: 'KestrelPlay platform', test: (p) => inT(p, 'play') },
    { id: 'broadcast', name: 'Broadcast continuity policy', short: 'Broadcast', ask: 'Playout and ingest systems keep an approved software baseline and vendor patch statement.', scopeLabel: 'Live & playout', test: (p) => inT(p, 'live') },
  ],
  healthcare: [
    { id: 'fda524b', name: 'FDA 524B (FD&C Act) · cyber devices', short: 'FDA 524B', ask: 'Manufacturers of cyber devices must provide an SBOM; Mercy Ridge makes the SBOM a procurement condition for every connected device.', scopeLabel: 'Medical devices', test: (p) => has(p, 'device') },
    { id: 'cpg', name: 'HHS HPH CPGs · vendor & asset inventory', short: 'HPH CPGs', ask: 'Know your assets and require vendors to disclose and fix known vulnerabilities in what they supply.', scopeLabel: 'All clinical systems', test: (p) => !inT(p, 'research') || p.tenants.length > 1 },
    { id: 'hipaa', name: 'HIPAA Security Rule 164.308(a)(1)', short: 'HIPAA', ask: 'Risk analysis covering every system that stores or moves ePHI, including embedded software.', scopeLabel: 'ePHI systems', test: (p) => !inT(p, 'research') || p.origin === 'Vendor' },
    { id: 'jc', name: 'Joint Commission / CMS conditions', short: 'CMS CoP', ask: 'Emergency preparedness: dependable clinical systems with known vendor support status.', scopeLabel: 'Hospital systems', test: (p) => inT(p, 'mrmc', 'kids', 'community') },
  ],
  automotive: [
    { id: 'r155', name: 'UNECE R155 (CSMS) 7.2.2.2', short: 'UN R155', ask: 'Manage supplier risk and monitor vehicle software for new vulnerabilities across the vehicle type’s life.', scopeLabel: 'Vehicle software', test: (p) => has(p, 'vehicle') },
    { id: 'r156', name: 'UNECE R156 (SUMS) · RXSWIN', short: 'UN R156', ask: 'Record every software version on each vehicle type and assess the impact of every update.', scopeLabel: 'Vehicle & OTA software', test: (p) => has(p, 'vehicle') },
    { id: 'iso21434', name: 'ISO/SAE 21434 cl. 8 & 15', short: 'ISO 21434', ask: 'Continuous cybersecurity monitoring of components, including open-source and supplier software.', scopeLabel: 'Vehicle software', test: (p) => has(p, 'vehicle') },
    { id: 'cra', name: 'EU Cyber Resilience Act', short: 'CRA', ask: 'Connected products outside type approval (app, home charger) need an SBOM and vulnerability handling.', scopeLabel: 'App & charger', test: (p) => p.origin === 'In-house' && has(p, 'app') },
    { id: 'iec62443', name: 'IEC 62443 / TISAX', short: 'IEC 62443', ask: 'Plant automation suppliers disclose components and patch status; vendor remote access controlled.', scopeLabel: 'Plant OT', test: (p) => has(p, 'ot') },
  ],
  insurance: [
    { id: 'nydfs', name: 'NYDFS 23 NYCRR 500.13 & 500.11', short: 'NYDFS 500', ask: 'A complete asset inventory covering software, owner and support status, and oversight of the security of what third-party service providers supply.', scopeLabel: 'All systems', test: () => true },
    { id: 'naic', name: 'NAIC Data Security Model Law (#668) §4', short: 'NAIC #668', ask: 'Risk assessment of every system holding nonpublic information, including oversight of third-party service providers and the software they run for Kingsbridge.', scopeLabel: 'NPI systems', test: (p) => inT(p, 'personal', 'commercial', 'claims', 'life') },
    { id: 'pci', name: 'PCI DSS v4.0.1 req. 6.3.2', short: 'PCI DSS', ask: 'Keep an inventory of bespoke and custom software and the third-party components in it, to manage vulnerabilities in the premium payment flows.', scopeLabel: 'Premium payments (CDE)', test: (p) => has(p, 'payments') },
    { id: 'clients', name: 'Commercial client & agency security schedules', short: 'Client terms', ask: 'Large commercial policyholders and agency partners ask for component disclosure and patch timelines for software that holds or exchanges their data.', scopeLabel: 'Client-facing systems', test: (p) => inT(p, 'commercial', 'specialty') || has(p, 'app') },
  ],
  defence: [
    { id: 'dfars', name: 'DFARS 252.204-7012 / NIST SP 800-171 (3.4.1, 3.11.2, 3.14.1)', short: 'DFARS 7012', ask: 'Baseline configurations and inventories for systems that process CUI, with vulnerabilities scanned and flaws fixed in a timely way.', scopeLabel: 'CUI systems', test: (p) => inT(p, 'programs', 'engineering', 'manufacturing') },
    { id: 'cmmc', name: 'CMMC Level 2 (32 CFR Part 170)', short: 'CMMC L2', ask: 'Assessors expect evidence of software inventory and flaw remediation for every in-scope asset, including OT handled as specialised assets.', scopeLabel: 'CMMC assessment scope', test: (p) => !inT(p, 'corporate') || p.tenants.length > 1 },
    { id: 'ssdf', name: 'EO 14028 / NIST SSDF (SP 800-218) attestation', short: 'SSDF', ask: 'Producers of software delivered to the US Government attest to secure development practices and provide an SBOM on request.', scopeLabel: 'Delivered software', test: (p) => p.origin === 'In-house' },
    { id: 'flowdown', name: 'Prime flow-downs (Lockheed Martin, RTX)', short: 'Prime flow-downs', ask: 'Subcontract terms ask for SBOMs and vulnerability notice within 72 hours for software and firmware delivered in, or used to build and test, deliverables.', scopeLabel: 'Deliverable & production software', test: (p) => inT(p, 'engineering', 'manufacturing', 'tucson') },
  ],
  pharma: [
    { id: 'cra', name: 'EU Cyber Resilience Act', short: 'CRA', ask: 'Products with digital elements placed on the EU market (patient-support app, connected autoinjector) need an SBOM and vulnerability handling for their support period.', scopeLabel: 'Connected products', test: (p) => p.origin === 'In-house' && has(p, 'app', 'device') },
    { id: 'fda524b', name: 'FDA 524B · combination-product cyber devices', short: 'FDA 524B', ask: 'Premarket submissions for a cyber device include an SBOM and a plan to monitor and fix vulnerabilities after release (RhenaPen autoinjector).', scopeLabel: 'Connected combination products', test: (p) => has(p, 'device') },
    { id: 'annex11', name: 'EU GMP Annex 11 / 21 CFR Part 11', short: 'Annex 11', ask: 'Validated computerised systems keep an up-to-date inventory of components and suppliers, with change control and impact assessment for every update.', scopeLabel: 'GxP systems', test: (p) => inT(p, 'valais', 'cork') || has(p, 'ot') },
    { id: 'nis2', name: 'NIS2 Art. 21(2)(d)–(e)', short: 'NIS2', ask: 'Supply-chain security and vulnerability handling for the software suppliers provide to an essential manufacturing entity.', scopeLabel: 'EU operations', test: (p) => !inT(p, 'commercial') || p.tenants.length > 1 },
  ],
  sghospital: [
    { id: 'hsa', name: 'HSA GL-04 medical device cybersecurity', short: 'HSA GL-04', ask: 'Connected medical devices come with an SBOM, a vulnerability-disclosure route and a support end date; Orchid Bay makes this a procurement condition.', scopeLabel: 'Medical devices', test: (p) => has(p, 'device') },
    { id: 'imdrf', name: 'IMDRF N73 (SBOM for medical devices)', short: 'IMDRF', ask: 'Healthcare providers use manufacturers’ SBOMs to assess new vulnerabilities across the device life cycle.', scopeLabel: 'Vendor medical devices', test: (p) => has(p, 'device') && p.origin === 'Vendor' },
    { id: 'hia', name: 'HIA · MOH Cybersecurity & Data Security Essentials', short: 'HIA CS/DS', ask: 'Keep an inventory of systems holding health information, with software versions and vendor support status, and patch within MOH timelines.', scopeLabel: 'Health-information systems', test: (p) => inT(p, 'obh', 'specialist', 'daysurg', 'labimg') },
    { id: 'ct', name: 'CSA Cyber Trust mark (asset & supplier management)', short: 'Cyber Trust', ask: 'Identify hardware and software assets and require suppliers to manage vulnerabilities in what they deliver.', scopeLabel: 'All systems', test: () => true },
  ],
  studio: [
    { id: 'cra', name: 'EU Cyber Resilience Act', short: 'CRA', ask: 'Starfall+ apps and the StarPass wearable offered in the EU need an SBOM and vulnerability handling for their support period.', scopeLabel: 'Connected consumer products', test: (p) => p.origin === 'In-house' && has(p, 'app') },
    { id: 'tpn', name: 'TPN Gold Shield (MPA CSBP)', short: 'TPN', ask: 'Tools that touch pre-release content are inventoried, supported and patched, and vendor applications are assessed.', scopeLabel: 'Content-handling tools', test: (p) => inT(p, 'studios', 'post') },
    { id: 'pci', name: 'PCI DSS v4.0.1 req. 6.3.2 & 6.4.3', short: 'PCI DSS', ask: 'Inventory bespoke software and its components, and authorise every script on payment pages (Starfall+, StarPass, ticketing).', scopeLabel: 'Payment flows', test: (p) => has(p, 'payments') },
    { id: 'iec62443', name: 'IEC 62443-2-4 / 4-1 (ride & show)', short: 'IEC 62443', ask: 'Ride and show suppliers disclose components and patch status; updates go through the ride safety change process.', scopeLabel: 'Parks OT', test: (p) => has(p, 'ot') },
  ],
};

/* =====================================================================
   Build (group-level, cached per customer)
   ===================================================================== */
interface Base { products: SbProduct[]; comps: SbComponent[]; byId: Map<string, SbComponent>; regs: SbReg[]; advComp: SbComponent }
const CACHE = new Map<CustomerId, Base>();

const FORMAT: Record<Exclude<Code, null | 'scan'>, SbFormat> = { c6: 'CycloneDX 1.6', c5: 'CycloneDX 1.5', s2: 'SPDX 2.3', s3: 'SPDX 3.0' };
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const conn = (c: CustomerProfile, re: RegExp) => c.connectors.find((k) => re.test(k.category));
const cname = (k?: { vendor: string; product: string }) => (k ? (k.vendor === 'Generic' || k.vendor === 'HexaShield' ? k.product : `${k.vendor} ${k.product}`) : '');

/** Which tool produced the SBOM for a given source. */
export function sbTool(c: CustomerProfile, src: SbSource, ot: boolean): string {
  if (src === 'Build pipeline') return cname(conn(c, /AppSec/)) || 'Build pipeline (CycloneDX plugin)';
  if (src === 'Generated by scan') return ot ? `HexaCore binary analysis${c.connectors.some((k) => k.category === 'OT') ? ` · ${cname(c.connectors.find((k) => k.category === 'OT'))}` : ''}` : `HexaCore binary analysis · ${cname(conn(c, /^Vulnerability$/)) || 'scanner'}`;
  return 'HexaCore SBOM intake · vendor portal';
}

function bumpDown(ver: string, r: ReturnType<typeof rng>): string {
  const m = ver.match(/^(.*?)(\d+)$/);
  if (!m) return ver;
  const n = Number(m[2]);
  return n > 0 ? `${m[1]}${Math.max(0, n - r.int(1, Math.min(3, n)))}` : ver;
}

function build(c: CustomerProfile): Base {
  const hit = CACHE.get(c.id);
  if (hit) return hit;
  const r = rng(`sbom-${c.id}`);
  const adv = vrAdvisory(c);
  const ac = forCustomer(ADV_COMP, c);
  const advComp: SbComponent = {
    id: slug(ac.name), name: ac.name, ecosystem: ac.ecosystem, category: ac.category, licence: ac.licence, licRisk: ac.licRisk, latest: ac.latest, maintainer: ac.maintainer ?? adv.vendor, desc: ac.desc, advisory: true,
    vulns: [{ id: adv.cve, sev: 'critical', cvss: adv.cvss, title: ac.vulnTitle, fixedIn: ac.latest, advisory: true }],
  };
  const comps: SbComponent[] = [advComp, ...[...GENERIC, ...forCustomer(SECTOR_LIBS, c)].map((s) => ({ ...s, id: slug(s.name), maintainer: s.maintainer ?? 'Open-source community', vulns: s.vulns ?? [] }))];
  const byId = new Map(comps.map((x) => [x.id, x]));
  const pool = comps.filter((x) => !x.advisory);
  const clean = pool.filter((x) => !x.vulns.length);
  const sups = tpSuppliers(c, 'all');
  const supId = (name?: string) => (name ? sups.find((s) => s.name === name)?.id : undefined);

  const pickVex = (pr: ReturnType<typeof rng>): SbVex => pr.weighted([['Affected', 3], ['Not affected', 4], ['Under investigation', 2], ['Fixed', 2]] as const);

  const products: SbProduct[] = forCustomer(PRODUCTS, c).map((s) => {
    const pr = rng(`sbom-${c.id}-${s.n}`);
    const origin: SbOrigin = s.o === 'I' ? 'In-house' : 'Vendor';
    const tags = s.tags ?? [];
    let sbom: SbSbom | null = null;
    if (s.s) {
      const source: SbSource = s.s === 'scan' ? 'Generated by scan' : origin === 'In-house' ? 'Build pipeline' : 'Vendor portal';
      const ageDays = source === 'Build pipeline' ? pr.int(0, 9) : source === 'Generated by scan' ? pr.int(3, 40) : pr.weighted([[pr.int(8, 60), 5], [pr.int(95, 240), 3]] as const);
      sbom = { format: s.s === 'scan' ? 'CycloneDX 1.6' : FORMAT[s.s], source, ageDays, signed: source === 'Build pipeline' ? true : pr.chance(0.55), tool: sbTool(c, source, tags.includes('ot')), serial: `urn:uuid:${pr.hex(8)}-${pr.hex(4)}-${pr.hex(4)}-${pr.hex(4)}-${pr.hex(12)}` };
    }
    // Dependency tree (only when an SBOM exists)
    const modules: SbModule[] = [];
    if (sbom) {
      const realSupplier = s.o === 'S';
      const libPool = realSupplier ? clean : pool;
      const modNames = s.mods ?? ['Core service', 'Web console', 'Update agent'];
      const used = new Set<string>();
      modNames.forEach((mn, mi) => {
        const n = pr.int(2, 4);
        const picks = pr.pickN(libPool.filter((x) => !used.has(x.id)), n);
        const libs: SbLib[] = picks.map((x) => {
          used.add(x.id);
          const vex: Record<string, SbVex> = {};
          let ver = x.latest;
          if (x.vulns.length) {
            const st = pickVex(pr);
            x.vulns.forEach((vv) => { vex[vv.id] = st; });
            ver = st === 'Fixed' ? x.vulns[0].fixedIn : bumpDown(x.vulns[0].fixedIn, pr);
          } else if (pr.chance(0.4)) ver = bumpDown(x.latest, pr);
          // a transitive dependency is sometimes pulled in through another library
          const via = mi > 0 && pr.chance(0.35) ? pr.pick(GENERIC.filter((g) => !g.vulns).map((g) => g.name)) : undefined;
          return { compId: x.id, version: ver, vex, via: via && via !== x.name ? via : undefined };
        });
        if (s.adv && mi === (s.adv === 'matched' ? 0 : modNames.length - 1)) {
          libs.unshift({ compId: advComp.id, version: s.advVer ?? adv.affectedVersions, vex: { [adv.cve]: s.advVex ?? 'Affected' } });
        }
        modules.push({ name: s.adv && mi === modNames.length - 1 && s.adv === 'hidden' ? `${mn} · ${ac.module}` : mn, version: `${pr.int(1, 9)}.${pr.int(0, 12)}.${pr.int(0, 20)}`, libs });
      });
    }
    return {
      id: `sb-${slug(s.n)}`.slice(0, 48), name: s.n, vendor: s.vendor, origin, category: s.cat, tenants: s.t, tags,
      supplierName: s.sup, supplierId: supId(s.sup), sbom,
      request: sbom ? 'Not requested' : (s.req ?? 'Not requested'), requestDaysAgo: sbom ? null : s.reqDays ?? null,
      componentCount: sbom ? (origin === 'In-house' ? r.int(380, 2400) : tags.includes('ot') || tags.includes('device') ? r.int(90, 620) : r.int(220, 1500)) : 0,
      modules, instances: s.inst ?? 1, criticality: s.crit ?? 3, adv: s.adv, note: s.note,
    };
  });

  const base: Base = { products, comps, byId, regs: forCustomer(REGS, c), advComp };
  CACHE.set(c.id, base);
  return base;
}

/* =====================================================================
   In-session store: SBOM requests sent from the page
   ===================================================================== */
const REQUESTED = new Map<string, number>(); // `${customer}:${productId}` -> epoch ms
const listeners = new Set<() => void>();
let version = 0;
export function sbSubscribe(l: () => void): () => void { listeners.add(l); return () => listeners.delete(l); }
export function sbVersion(): number { return version; }
export function sbRequestSbom(c: CustomerProfile, productId: string) {
  REQUESTED.set(`${c.id}:${productId}`, Date.now());
  version++;
  listeners.forEach((l) => l());
}

/* =====================================================================
   Public API
   ===================================================================== */
export interface SbData {
  products: SbProduct[];
  comps: SbCompRow[];
  regs: SbRegRow[];
  advComp: SbComponent;
  byId: Map<string, SbComponent>;
  kpi: {
    total: number; withSbom: number; missing: number; stale: number; fresh: number; freshPct: number; medianAge: number;
    tracked: number; vulnerable: number; suppressed: number; licence: number; vulnInstances: number;
  };
}

function median(a: number[]): number {
  if (!a.length) return 0;
  const s = [...a].sort((x, y) => x - y);
  return s[Math.floor(s.length / 2)];
}

const SEV_RANK: Record<Severity, number> = { critical: 4, high: 3, medium: 2, low: 1, info: 0 };

export function sbData(c: CustomerProfile, tenantId: string): SbData {
  const b = build(c);
  const products = b.products
    .filter((p) => tenantId === 'all' || p.tenants.includes(tenantId))
    .map((p) => {
      const at = REQUESTED.get(`${c.id}:${p.id}`);
      return at && !p.sbom ? { ...p, request: 'Requested' as SbRequest, requestDaysAgo: 0 } : p;
    });
  const uses = new Map<string, SbUsage[]>();
  products.forEach((p) => p.modules.forEach((m) => m.libs.forEach((l) => {
    const arr = uses.get(l.compId) ?? [];
    arr.push({ product: p, module: m.name, lib: l });
    uses.set(l.compId, arr);
  })));
  const comps: SbCompRow[] = b.comps
    .filter((x) => uses.has(x.id))
    .map((x) => {
      const u = uses.get(x.id)!;
      const vex: Record<SbVex, number> = { Affected: 0, 'Under investigation': 0, 'Not affected': 0, Fixed: 0 };
      u.forEach((us) => Object.values(us.lib.vex).forEach((s) => { vex[s]++; }));
      const open = vex.Affected + vex['Under investigation'];
      const maxSev = x.vulns.length ? x.vulns.reduce<Severity>((m, vv) => (SEV_RANK[vv.sev] > SEV_RANK[m] ? vv.sev : m), 'info') : null;
      const distributed = u.some((us) => us.product.origin === 'In-house' || us.product.tags.includes('vehicle'));
      return {
        c: x, uses: u, products: new Set(u.map((us) => us.product.id)).size, versions: [...new Set(u.map((us) => us.lib.version))],
        vex, maxSev, open, vulnerable: open > 0,
        licFlag: x.licRisk === 'Unknown' || (x.licRisk === 'Strong copyleft' && distributed),
      };
    });
  const withSb = products.filter((p) => p.sbom);
  const ages = withSb.map((p) => p.sbom!.ageDays);
  const stale = ages.filter((a) => a > SB_STALE_DAYS).length;
  const regs: SbRegRow[] = b.regs.map((reg) => {
    const inScope = products.filter(reg.test);
    const withSbom = inScope.filter((p) => p.sbom);
    return { reg, inScope, withSbom, pct: inScope.length ? Math.round((withSbom.length / inScope.length) * 100) : 100 };
  });
  return {
    products, comps, regs, advComp: b.advComp, byId: b.byId,
    kpi: {
      total: products.length, withSbom: withSb.length, missing: products.length - withSb.length, stale, fresh: withSb.length - stale,
      freshPct: withSb.length ? Math.round(((withSb.length - stale) / withSb.length) * 100) : 0, medianAge: median(ages),
      tracked: Math.round(withSb.reduce((s, p) => s + p.componentCount, 0) * 0.46),
      vulnerable: comps.filter((x) => x.vulnerable).length,
      suppressed: comps.reduce((s, x) => s + x.vex['Not affected'], 0),
      licence: comps.filter((x) => x.licFlag).length,
      vulnInstances: comps.reduce((s, x) => s + x.vex.Affected + x.vex['Under investigation'] + x.vex['Not affected'] + x.vex.Fixed, 0),
    },
  };
}

export function sbProduct(d: SbData, id: string | null): SbProduct | undefined {
  return id ? d.products.find((p) => p.id === id) : undefined;
}
export function sbComp(d: SbData, id: string | null): SbCompRow | undefined {
  return id ? d.comps.find((x) => x.c.id === id) : undefined;
}

/** Vulnerable libraries in a product (VEX affected or under investigation). */
export function sbProductVulns(p: SbProduct, byId: Map<string, SbComponent>): { comp: SbComponent; lib: SbLib; module: string; vex: SbVex; vuln: SbVuln }[] {
  const out: { comp: SbComponent; lib: SbLib; module: string; vex: SbVex; vuln: SbVuln }[] = [];
  p.modules.forEach((m) => m.libs.forEach((l) => {
    const comp = byId.get(l.compId);
    if (!comp) return;
    comp.vulns.forEach((vv) => { const s = l.vex[vv.id]; if (s) out.push({ comp, lib: l, module: m.name, vex: s, vuln: vv }); });
  }));
  return out;
}

/* =====================================================================
   Hidden exposure for the headline advisory
   ===================================================================== */
export interface SbAdvExposure {
  cve: string;
  advId: string;
  advProduct: string;
  vendor: string;
  comp: SbComponent;
  matched: SbProduct[];
  hidden: SbProduct[];
  hiddenInstances: number;
  assetMatched: number;
}

/** Products whose SBOM contains the component behind the headline advisory. Null when `cve` is not the headline. */
export function sbAdvisoryExposure(c: CustomerProfile, tenantId: string, cve?: string): SbAdvExposure | null {
  const adv = vrAdvisory(c);
  if (cve && cve !== adv.cve) return null;
  const d = sbData(c, tenantId);
  const inside = d.products.filter((p) => p.modules.some((m) => m.libs.some((l) => l.compId === d.advComp.id)));
  const hidden = inside.filter((p) => p.adv === 'hidden');
  return {
    cve: adv.cve, advId: adv.id, advProduct: adv.product, vendor: adv.vendor, comp: d.advComp,
    matched: inside.filter((p) => p.adv === 'matched'), hidden,
    hiddenInstances: hidden.reduce((s, p) => s + p.instances, 0),
    assetMatched: vrAssets(c, tenantId, adv).length,
  };
}

/** Where a product sits in a component: module and lib. */
export function sbUsageOf(p: SbProduct, compId: string): { module: string; lib: SbLib } | undefined {
  for (const m of p.modules) for (const l of m.libs) if (l.compId === compId) return { module: m.name, lib: l };
  return undefined;
}

export function sbSources(c: CustomerProfile): { name: string; status?: Health }[] {
  const appsec = conn(c, /AppSec/);
  const ot = c.connectors.find((k) => k.category === 'OT');
  return [
    { name: 'HexaCore SBOM intake' },
    { name: appsec ? cname(appsec) : 'Build pipeline plugin' },
    { name: cname(conn(c, /^Vulnerability$/)) || 'Scanner' },
    ...(ot ? [{ name: cname(ot) }] : []),
    { name: 'HexaComply TPRM' },
  ];
}
