import { Siren, ArrowRight } from 'lucide-react';
import { Card, Btn, Sources } from '../../../components/ui';
import { SEV_HEX } from '../../../components/Chart';
import { BarList, SegRows, RingLegend } from '../../insurance/viz';
import { fmtNum, plural } from '../../../lib/format';
import { SB_VEX, SB_VEX_HEX, SB_SOURCE_HEX, SB_STALE_DAYS, sbSources, type SbProduct, type SbSource } from '../../../data/modules/sbom';
import { TONE } from '../parts';
import type { SbCtx } from './ui';

const SRC_PARTS: (SbSource | 'Stale' | 'Missing')[] = ['Build pipeline', 'Vendor portal', 'Generated by scan', 'Stale', 'Missing'];
const PART_HEX: Record<(typeof SRC_PARTS)[number], string> = { ...SB_SOURCE_HEX, Stale: '#f0a338' };

function parts(ps: SbProduct[]) {
  return SRC_PARTS.map((k) => ({
    label: k === 'Stale' ? `Stale (> ${SB_STALE_DAYS} d)` : k,
    color: PART_HEX[k],
    value: ps.filter((p) => (k === 'Missing' ? !p.sbom : k === 'Stale' ? p.sbom && p.sbom.ageDays > SB_STALE_DAYS : p.sbom && p.sbom.ageDays <= SB_STALE_DAYS && p.sbom.source === k)).length,
  }));
}

export function Overview({ ctx }: { ctx: SbCtx }) {
  const { c, d, exp, go, openComp, tenantId, tenantShort } = ctx;
  const groups: { id: string; label: string; sub: string; ps: SbProduct[] }[] = [
    { id: 'In-house', label: 'In-house builds', sub: 'your own apps & firmware', ps: d.products.filter((p) => p.origin === 'In-house') },
    { id: 'Vendor', label: 'Vendor products', sub: 'bought software & devices', ps: d.products.filter((p) => p.origin === 'Vendor' && !p.supplierName) },
    { id: 'Supplier', label: 'TPRM suppliers', sub: 'in the third-party register', ps: d.products.filter((p) => !!p.supplierName) },
  ];
  const tenants = c.tenants.filter((t) => tenantId === 'all' ? true : t.id === tenantId).map((t) => ({ t, ps: d.products.filter((p) => p.tenants.includes(t.id)) })).filter((x) => x.ps.length);
  const top = [...d.comps].filter((x) => x.open > 0).sort((a, b) => (b.c.advisory ? 1 : 0) - (a.c.advisory ? 1 : 0) || b.open - a.open || b.products - a.products).slice(0, 8);
  const vexTot = SB_VEX.reduce((s, k) => s + d.comps.reduce((n, x) => n + x.vex[k], 0), 0);
  const vexBy = Object.fromEntries(SB_VEX.map((k) => [k, d.comps.reduce((n, x) => n + x.vex[k], 0)]));
  const withSb = d.products.filter((p) => p.sbom);
  const buckets = [
    { label: '0–30 days', test: (a: number) => a <= 30, color: '#2dd4bf', stale: false },
    { label: '31–90 days', test: (a: number) => a > 30 && a <= 90, color: '#4f8cff', stale: false },
    { label: '91–180 days', test: (a: number) => a > 90 && a <= 180, color: '#f0a338', stale: true },
    { label: 'Over 180 days', test: (a: number) => a > 180, color: '#e0345e', stale: true },
  ];
  const formats = [...new Set(withSb.map((p) => p.sbom!.format))].sort();

  return (
    <div className="sb-stack">
      <div className="grid g-3-2">
        <Card title="SBOM coverage" sub="Every software product, by where its SBOM comes from · click a row for the products" foot={<Sources items={sbSources(c)} />}>
          <SegRows
            legend
            labelWidth={160}
            rows={[
              ...groups.filter((g) => g.ps.length).map((g) => ({ label: g.label, sub: g.sub, parts: parts(g.ps), onClick: () => go('products', { origin: g.id }) })),
              ...tenants.map(({ t, ps }) => ({ label: t.short, sub: t.kind, parts: parts(ps), onClick: () => go('products', { site: t.id }) })),
            ]}
          />
        </Card>
        <Card title="Top vulnerable components" sub="Open vulnerability instances (VEX affected or under investigation) · click for every product it is inside">
          {top.length ? (
            <BarList
              labelWidth={170}
              items={top.map((x) => ({
                label: <span className="mono">{x.c.name}</span>,
                sub: `${x.c.vulns.map((v) => v.id).join(', ')} · in ${plural(x.products, 'product')}`,
                value: x.open,
                display: `${x.open}`,
                color: x.maxSev ? SEV_HEX[x.maxSev === 'info' ? 'low' : x.maxSev] : TONE,
                onClick: () => openComp(x.c.id),
              }))}
            />
          ) : <div className="empty">No open vulnerable components in scope.</div>}
        </Card>
      </div>

      <div className="grid g-1-2">
        <Card title="Hidden exposure" sub={exp ? `${exp.cve} · ${exp.advProduct}` : 'Headline advisory'} toneColor="var(--sev-critical)" actions={<Btn sm onClick={() => go('hidden')}>Open <ArrowRight size={13} /></Btn>}>
          {exp && exp.hidden.length ? (
            <div className="stack" style={{ gap: 12 }}>
              <div className="sb-trio">
                <button type="button" onClick={() => go('hidden')} title="Source: SBOM components × the headline advisory"><b style={{ color: 'var(--sev-critical)' }}>{exp.hidden.length}</b><span>vendor products</span></button>
                <button type="button" onClick={() => go('hidden')} title="Source: HexaCore asset inventory"><b>{fmtNum(exp.hiddenInstances)}</b><span>installed units</span></button>
                <button type="button" onClick={() => go('hidden')} title="Source: HexaInt Critical Vulnerability Response"><b style={{ color: 'var(--text-muted)' }}>0</b><span>seen by asset match</span></button>
              </div>
              <p className="sb-muted" style={{ margin: 0, fontSize: 12, lineHeight: 1.5 }}>
                <Siren size={12} style={{ verticalAlign: -2, color: 'var(--sev-critical)' }} /> The asset match found {plural(exp.assetMatched, 'asset')} running {exp.advProduct}. The same vulnerable library sits inside {exp.hidden.map((p) => p.name).join(', ')}, which report their own names and versions to scanners.
              </p>
            </div>
          ) : (
            <div className="empty">No vendor product in {ctx.tenantId === 'all' ? c.short : tenantShort(ctx.tenantId)} embeds the component behind {exp?.cve ?? 'the headline advisory'}.</div>
          )}
        </Card>
        <Card title="Sector regulation" sub={`What ${c.short}'s regulators and customers expect of software supply chains · SBOM coverage of the products in scope`}>
          <div className="sb-regs">
            {d.regs.map((r) => {
              const col = r.pct >= 85 ? 'var(--good)' : r.pct >= 60 ? 'var(--sev-medium)' : 'var(--sev-critical)';
              return (
                <button key={r.reg.id} type="button" className="sb-reg" onClick={() => go('products', { reg: r.reg.id })} title={`${r.reg.name} · click for the ${r.inScope.length} products in scope`}>
                  <span>
                    <span className="sb-reg-h"><b>{r.reg.name}</b><span>{r.reg.scopeLabel}</span></span>
                    <p>{r.reg.ask}</p>
                  </span>
                  <span className="sb-reg-cov">
                    <b style={{ color: r.inScope.length ? col : 'var(--text-muted)' }}>{r.inScope.length ? `${r.pct}%` : 'n/a'}</b>
                    <span className="sb-reg-track"><i style={{ width: `${r.pct}%`, background: col }} /></span>
                    <small>{r.withSbom.length} of {r.inScope.length} with SBOM</small>
                  </span>
                </button>
              );
            })}
          </div>
        </Card>
      </div>

      <div className="grid g3">
        <Card title="VEX triage" sub="Every vulnerability found in an SBOM, by exploitability statement">
          <RingLegend
            value={vexBy['Not affected'] + vexBy.Fixed}
            max={Math.max(1, vexTot)}
            color="#2dd4bf"
            center={fmtNum(vexTot)}
            centerSub="findings"
            size={112}
            rows={SB_VEX.map((k) => ({ label: k, value: fmtNum(vexBy[k]), color: SB_VEX_HEX[k], onClick: () => go('components', { vex: k }) }))}
          />
          <p className="sb-muted" style={{ margin: '10px 0 0', fontSize: 11.5, lineHeight: 1.45 }}>
            {vexTot ? `${Math.round(((vexBy['Not affected'] + vexBy.Fixed) / vexTot) * 100)}% of raw SBOM matches are suppressed by a VEX statement, so engineers chase only what is exploitable.` : 'No vulnerability matches in scope.'}
          </p>
        </Card>
        <Card title="SBOM freshness" sub={`Age of the latest SBOM per product · stale after ${SB_STALE_DAYS} days`}>
          <BarList
            labelWidth={110}
            items={[
              ...buckets.map((b) => ({ label: b.label, value: withSb.filter((p) => b.test(p.sbom!.ageDays)).length, color: b.color, onClick: () => go('products', { sbom: b.stale ? 'stale' : 'yes' }) })),
              { label: 'No SBOM', value: d.kpi.missing, color: '#8593b4', onClick: () => go('products', { sbom: 'missing' }) },
            ]}
          />
        </Card>
        <Card title="Formats & sources" sub="How SBOMs arrive">
          <BarList
            labelWidth={130}
            items={[
              ...formats.map((f) => ({ label: f, value: withSb.filter((p) => p.sbom!.format === f).length, color: f.startsWith('Cyclone') ? '#4f8cff' : '#a07cfb', onClick: () => go('products', { sbom: 'yes' }) })),
              ...(['Build pipeline', 'Vendor portal', 'Generated by scan'] as SbSource[]).map((s) => ({ label: s, sub: s === 'Generated by scan' ? 'binary analysis' : undefined, value: withSb.filter((p) => p.sbom!.source === s).length, color: SB_SOURCE_HEX[s], onClick: () => go('products', { src: s }) })),
            ]}
          />
          <p className="sb-muted" style={{ margin: '10px 0 0', fontSize: 11.5 }}>{withSb.filter((p) => p.sbom!.signed).length} of {withSb.length} SBOMs are signed by their producer.</p>
        </Card>
      </div>
    </div>
  );
}
